// Generated by scripts/derive-ldraw-catalog-frames.mjs from the byte-pinned official
// LDraw archive ldraw-complete-2026-07.zip (144722356 bytes,
// sha256:6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae). Do not hand-edit. Reproduce with:
//
//   node scripts/derive-ldraw-catalog-frames.mjs --official <ldraw-complete-2026-07.zip> --write
//
// and check with --check. Each row is measurement only: the orientation and
// whole-LDU offset that put the file's extent and studs on the catalog part
// (catalog = O * ldraw + t), plus the root file's identity and attribution.

import type { LdrawInterchangeFrameRow } from "./ldraw-interchange-frames.ts";

export const LDRAW_INTERCHANGE_FRAME_ARCHIVE = {
  logicalName: "ldraw-complete-2026-07.zip",
  bytes: 144722356,
  sha256: "sha256:6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae",
} as const;

/** One row per parametric catalog part, by LDraw id. */
export const LDRAW_INTERCHANGE_FRAME_ROWS: readonly LdrawInterchangeFrameRow[] = Object.freeze([
  // prettier-ignore
  { ldrawId: "15573.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:c6946965875a8275996c4559cd355ea13a20197e96f33585cd750bb1da89b56d", rootBytes: 2327, closureFileCount: 11, title: "Plate  1 x  2 with Groove with 1 Centre Stud, without Understud", author: "Magnus Forsberg [MagFors]", ldrawOrg: "Part UPDATE 2013-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2412b.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:a7e7b03fc76cad9d94eb7199721b929f95227b1f8a35add5b7c66ee1ba6dca57", rootBytes: 2820, closureFileCount: 6, title: "Tile  1 x  2 Grille with Groove", author: "Guy Vivan [guyvivan]", ldrawOrg: "Part UPDATE 2009-01", licenseExpression: "CC-BY-2.0 OR CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2420.dat", orientationId: "upright-yaw-0", translationLdu: [-10, -4, -10], basis: "derived", candidates: 1, rootSha256: "sha256:ded452d47f31f69b4c3128674ee851f7ae05205230c4e414ce2823b3b014d384", rootBytes: 1329, closureFileCount: 7, title: "Plate  2 x  2 Corner", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2431.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:8e5999a1352d8204101b2311ca435f88c7d7af20fb8214fa588e9bacd3942315", rootBytes: 347, closureFileCount: 8, title: "Tile  1 x  4 with Groove", author: "Santeri Piippo [arezey]", ldrawOrg: "Part UPDATE 2010-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2445.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:1a5bb74442dd985894e46af12d0e313856ba08d9d7c6f7ae4fc3b262e6df0942", rootBytes: 2182, closureFileCount: 8, title: "Plate  2 x 12", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2456.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:59137cf0481aef7fffd3635459813bae50f67869612f64c88e7fcf6f3fd8d384", rootBytes: 1438, closureFileCount: 8, title: "Brick  2 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2009-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "2465.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:3237acda8a54e8835b93abd983b847ff1921d05d8ff52a8e1f3c47f88d98ec64", rootBytes: 539, closureFileCount: 8, title: "Brick  1 x 16", author: "James Jessiman", ldrawOrg: "Part UPDATE 2009-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3001.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:70968cb5e4baa92dc6a1939aca7526b8566a17dbea49da9b91182aa864e412c4", rootBytes: 663, closureFileCount: 10, title: "Brick  2 x  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2004-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3002.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:02065cff45c9f5cbc52259757813d3ac66e013777b759bf35a6bb94c9cbf1681", rootBytes: 681, closureFileCount: 9, title: "Brick  2 x  3", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3003.dat", orientationId: "upright-yaw-0", translationLdu: [0, -12, 0], basis: "derived", candidates: 4, rootSha256: "sha256:aed0ccd750126a58d38b012a4e8b16c172896339547c120ef67b69e1386f490d", rootBytes: 670, closureFileCount: 12, title: "Brick  2 x  2", author: "James Jessiman", ldrawOrg: "Part UPDATE 2022-05", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3004.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:e1caee3b32175393c9d6ea176a47f8869173a01d03a451e1cfe10d09167c0203", rootBytes: 670, closureFileCount: 9, title: "Brick  1 x  2", author: "James Jessiman", ldrawOrg: "Part UPDATE 2022-05", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3005.dat", orientationId: "upright-yaw-0", translationLdu: [0, -12, 0], basis: "derived", candidates: 4, rootSha256: "sha256:f86e5f3aed432cab8f5dffcf2e41a9f2ee8c3bd4dcad1732da9630837849a4f8", rootBytes: 670, closureFileCount: 8, title: "Brick  1 x  1", author: "James Jessiman", ldrawOrg: "Part UPDATE 2022-05", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3006.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:fe6499b0e1b98113d736330debd5809665737c9c7b0c9345af8a673a793be905", rootBytes: 2141, closureFileCount: 8, title: "Brick  2 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3007.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:56d95663f63adcf860757d84a9e664a6359fbc51d7b0b425afe03186402b9696", rootBytes: 667, closureFileCount: 16, title: "Brick  2 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2014-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3008.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:961b645476d8ae0a68c7c9a12be0521510737ad2b1eecd690302912a8dc81828", rootBytes: 673, closureFileCount: 11, title: "Brick  1 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2004-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3009.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:950a186800b17a778e6c4b91420b1846df98c2bdbac8a551cfe7f74ddc831a3e", rootBytes: 683, closureFileCount: 8, title: "Brick  1 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3010.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:7d1cb3082199042666045d92388b3b3ab697f969268e87a6c001f80f92a2e0b2", rootBytes: 788, closureFileCount: 11, title: "Brick  1 x  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3020.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:551e433cc4bcfdeeb6e390e509d52ee2e62c90d3eae625ee36928ef32291bb79", rootBytes: 1341, closureFileCount: 8, title: "Plate  2 x  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3021.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:ad56a79b7c774b99d30a54bd1e198ab95918ba3d1bcfc6a788ca15cf05d757e8", rootBytes: 1213, closureFileCount: 8, title: "Plate  2 x  3", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3022.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:3cd09bfe626e751ad95eab0ea83e5f3adea81f05d34993a1c4bf432ee386fe25", rootBytes: 1088, closureFileCount: 8, title: "Plate  2 x  2", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3023.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:fa3eeab92b077488bae3dbc0fe974ef3327a77f130776d2965f13d3ebc22ab57", rootBytes: 391, closureFileCount: 11, title: "~Moved to 3023b", author: "Orion Pobursky [OrionP]", ldrawOrg: "Part UPDATE 2024-07", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3024.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:e053af4f232374b0c8da2dc0f9620bedf0576ca43d7c3ceebc6676050ae61da8", rootBytes: 668, closureFileCount: 8, title: "Plate  1 x  1", author: "James Jessiman", ldrawOrg: "Part UPDATE 2022-05", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3027.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:5c564134cbf0f83f96064ea8f2da56d69a4dd8076d6e83e2c99d4f98274dc2c8", rootBytes: 8273, closureFileCount: 8, title: "Plate  6 x 16", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3028.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:52dfb92f2351b6a6ba5cc00039be58bc024ca50697d6d7aeae5d02a308b6fd33", rootBytes: 6345, closureFileCount: 8, title: "Plate  6 x 12", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3029.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:f4da0afd027802018b76267e98acdc485e7e6c45616738b424364aa7742e3f15", rootBytes: 4366, closureFileCount: 8, title: "Plate  4 x 12", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3030.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:9bb7ea91f82cc37dca948eb1624b5f0c877756a1afdec89692289adef5b7efef", rootBytes: 3740, closureFileCount: 8, title: "Plate  4 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3031.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:e67436538e47cb38b8352e91c2b5b7c7c274e070912603e5e9fc0b4513962338", rootBytes: 1938, closureFileCount: 8, title: "Plate  4 x  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3032.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:35e8b828a5bf21de83ca898a49b9725e6d08d5752ad6eb57910f27086108ca1f", rootBytes: 2535, closureFileCount: 8, title: "Plate  4 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2002-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3033.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:fccb28156f2a418eb0e9dc4f73cf51da4f13c5f5dadaa76e5bb643273e8c2067", rootBytes: 5224, closureFileCount: 8, title: "Plate  6 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3034.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:035f4ac31ecad8943fd0ac6baa155c6ff38c75a4d8ef1083fb2afa48b166a845", rootBytes: 1704, closureFileCount: 8, title: "Plate  2 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3035.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:325a0682753f92e97145d8e750cd86ac31af565a852554725f9bff27a1fd8cb8", rootBytes: 3111, closureFileCount: 8, title: "Plate  4 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3036.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:3074a0b2952f5d9903ac2fe2196a8110e1553fd245a1d8bc7ccb43f99c654d38", rootBytes: 4396, closureFileCount: 8, title: "Plate  6 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3068b.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:57179cd9dc0ee31742b9947157636b1b5eafc8d98a283fbd99e9abf8fda977ec", rootBytes: 804, closureFileCount: 9, title: "Tile  2 x  2 with Groove", author: "Takeshi Takahashi [RainbowDolphin]", ldrawOrg: "Part UPDATE 2024-06", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3069b.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:31203056de061c115b007f68a564bb2383761844b9373098df0c94cc4b18046a", rootBytes: 379, closureFileCount: 4, title: "Tile  1 x  2 with Groove", author: "Santeri Piippo [arezey]", ldrawOrg: "Part UPDATE 2010-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3070b.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:c7608c7e9f40c61747fb46c7107ef141b0a441e381768d2cdac0129f8ad03752", rootBytes: 477, closureFileCount: 4, title: "Tile  1 x  1 with Groove", author: "Chris Dee [cwdee]", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "32062.dat", orientationId: "upright-yaw-0", translationLdu: [0, 0, 0], basis: "reviewed-choice", candidates: 2, rootSha256: "sha256:5d5a970dccccabbd0a0e89e9519c69a51e6a8c75a35af1cfbf61f4fb46231da7", rootBytes: 6616, closureFileCount: 5, title: "Technic Axle  2 Notched", author: "Steve Bliss [sbliss]", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "34103.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:81e985e6dce3d56bec5fe2226b16139e38474f2fd1ff63ab4fa6fbdaf8b7b2f4", rootBytes: 522, closureFileCount: 13, title: "Plate  1 x  3 with  2 Studs Offset", author: "Magnus Forsberg [MagFors]", ldrawOrg: "Part UPDATE 2022-06", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3460.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:a236ed5a1efb4844f2eebafc6096a90571607af30e287b307400dcdea44f438f", rootBytes: 622, closureFileCount: 11, title: "Plate  1 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2024-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3483.dat", orientationId: "upright-yaw-90", translationLdu: [0, 0, 0], basis: "reviewed-choice", candidates: 2, rootSha256: "sha256:23320d45840f31f6385d34090ddc7fe7b8495eb3b66a83d189c18b4c19b52401", rootBytes: 51574, closureFileCount: 1, title: "Tyre  7/ 56 x 17 Offset Tread", author: "James Jessiman", ldrawOrg: "Part UPDATE 2014-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3622.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:9317bcec4fbcddbd38ed3972d25ea95d685101904f3ed86c7e769a9f356245d8", rootBytes: 511, closureFileCount: 11, title: "Brick  1 x  3", author: "James Jessiman", ldrawOrg: "Part UPDATE 2004-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3623.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:08f74845fceb4b39976d8ba56c0d59970483b8956cc59eb08e9f01ca579467e2", rootBytes: 616, closureFileCount: 10, title: "Plate  1 x  3", author: "James Jessiman", ldrawOrg: "Part UPDATE 2017-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3666.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:f4fc83d8c3fc1df32c1a217dc09775a99fad1ced348cffc5167f9c6a69aa9bca", rootBytes: 622, closureFileCount: 11, title: "Plate  1 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2023-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3700.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:6cb6522c580754cf970dad0fae688bb78cb3253a7237038dad83965fe47cfec6", rootBytes: 2367, closureFileCount: 17, title: "Technic Brick  1 x  2 with Hole", author: "James Jessiman", ldrawOrg: "Part UPDATE 2010-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3705.dat", orientationId: "upright-yaw-0", translationLdu: [0, 0, 0], basis: "derived", candidates: 2, rootSha256: "sha256:ed90738971675e2dbd05b5a0aecaccf2da32e62b4e9085b886f084de890a853a", rootBytes: 653, closureFileCount: 4, title: "Technic Axle  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3710.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:1a2d17e3e35750ccf02a54c7aee0cf7485c1c8596492746fc798d341399a3a6e", rootBytes: 622, closureFileCount: 11, title: "Plate  1 x  4", author: "James Jessiman", ldrawOrg: "Part UPDATE 2023-06", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3795.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:3a18cdb8f18fe9dba6fae79b525aee17be8bee71ea75fce3a794724d2a9b672f", rootBytes: 1502, closureFileCount: 8, title: "Plate  2 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2025-09", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3832.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:4928810faf064116f14126735c7a273df15c662fe1d648991c3a3c4cc79b0d49", rootBytes: 1917, closureFileCount: 8, title: "Plate  2 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "3958.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:9f64b46369f84ca4b172fd1a9e239cfd9bc17801d0999c38ef8847bf683e1dac", rootBytes: 898, closureFileCount: 15, title: "Plate  6 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2017-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "41539.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:8b07f1bb13a223f20d2587560540a584d99fdab788c234168e57c18ad796d084", rootBytes: 5591, closureFileCount: 8, title: "Plate  8 x  8", author: "Martin G Cormier", ldrawOrg: "Part UPDATE 2004-04", licenseExpression: "CC-BY-2.0 OR CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "4162.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:558dae4d9439dfcf4290601873fb2e3ca7387dbe6c29a9478a12003ea604f8e9", rootBytes: 718, closureFileCount: 9, title: "Tile  1 x  8", author: "James Jessiman", ldrawOrg: "Part UPDATE 2012-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "4477.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:4530db7fa36dc6039661336b73d0bf3ea80d8a6d24a8638e57f16d8fe20c501f", rootBytes: 1473, closureFileCount: 7, title: "Plate  1 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2003-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "60479.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:4cc9f46de13bd157dbbf16757bed1becee52253848fc1827d6c18477b94907b3", rootBytes: 1484, closureFileCount: 7, title: "Plate  1 x 12", author: "Philippe Hurbain [Philo]", ldrawOrg: "Part UPDATE 2009-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "6111.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:47beeadaec767df2caa76362bdd3d6a46e7439b822e3548cc75f638a76b7ec8c", rootBytes: 1510, closureFileCount: 7, title: "Brick  1 x 10", author: "James Jessiman", ldrawOrg: "Part UPDATE 2009-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "6112.dat", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0], basis: "derived", candidates: 2, rootSha256: "sha256:e903ef598ca391d4481d7c117c2fc8c33294c7b59607688137d8aefaa608c710", rootBytes: 1689, closureFileCount: 7, title: "Brick  1 x 12", author: "James Jessiman", ldrawOrg: "Part UPDATE 2009-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "63864.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:040f04315bec9f44a0250220303aa74c9661e6a8f26c2539a80effee0a27887d", rootBytes: 433, closureFileCount: 8, title: "Tile  1 x  3", author: "Tim Gould [timgould]", ldrawOrg: "Part UPDATE 2019-01", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "6636.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:e4bd77135a542e0953fd9d6e08e050911ce920582f0e1020f02bedcd9cbee84d", rootBytes: 729, closureFileCount: 9, title: "Tile  1 x  6", author: "James Jessiman", ldrawOrg: "Part UPDATE 2009-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "69729.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:2145aca5aa453d2a7ba512fb6be58ce7a77e9136fbbc137536aa759ef377ec61", rootBytes: 334, closureFileCount: 9, title: "Tile  2 x  6", author: "Vincent Messenet [Cheenzo]", ldrawOrg: "Part UPDATE 2020-03", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "87079.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:bb9846478e000ce54f7ffad0ea82cb9e4a3e98e1a1b8d04799d4b26a2ac52eeb", rootBytes: 570, closureFileCount: 8, title: "Tile  2 x  4", author: "Tim Gould [timgould]", ldrawOrg: "Part UPDATE 2025-04", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "87580.dat", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0], basis: "derived", candidates: 4, rootSha256: "sha256:9f1fee81902d00778bb6e91d6239d83ac6e3fca788954f30bbaab149abff6d54", rootBytes: 665, closureFileCount: 12, title: "Plate  2 x  2 with Groove with 1 Centre Stud", author: "Joerg Sommerer [Brickaneer]", ldrawOrg: "Part UPDATE 2017-01", licenseExpression: "CC-BY-2.0 OR CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "91988.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:873411a516fab0f053bbbf77cfd8d9babc64647d6432400a42a0026635debb42", rootBytes: 859, closureFileCount: 10, title: "Plate  2 x 14", author: "Owen Burgoyne [C3POwen]", ldrawOrg: "Part UPDATE 2012-02", licenseExpression: "CC-BY-4.0" },
  // prettier-ignore
  { ldrawId: "92438.dat", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0], basis: "derived", candidates: 2, rootSha256: "sha256:d180860e2598fa2576ef9d7af7084179c04bf5f5092662c491ee1b90576657e4", rootBytes: 765, closureFileCount: 16, title: "Plate  8 x 16", author: "Rolf Osterthun [Rolf]", ldrawOrg: "Part UPDATE 2011-01", licenseExpression: "CC-BY-4.0" },
]);
