// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

/**
 * Closed reviewed source class for the nominal measured-stud profile.
 * Connector authority and visible-stud LDraw ancestry are independent pins.
 */
export const SET_6651557_NOMINAL_STUD_SOURCE_CLASS = [
  {
    designId: "35480",
    connectorAuthority: "builder",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud2a.dat",
        sha256: "sha256:61fbed54b085a30490045309778d1e2a6d95485e6558996b12674f848028d557",
      },
    ],
  },
  {
    designId: "51739",
    connectorAuthority: "builder",
    studCount: 4,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-2x2.dat",
        sha256: "sha256:16114159ea25719341a852d5403dc9982a6211f2fcb23f5c4c3eac05a2ad43f7",
      },
    ],
  },
  {
    designId: "77844",
    connectorAuthority: "builder",
    studCount: 5,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-1x3.dat",
        sha256: "sha256:f24de368545aa96580b811daa6c25e18f5bfdbaca1d4b11addcfa7cbb625f4c9",
      },
      {
        archiveId: "official",
        path: "p/stug-2x1.dat",
        sha256: "sha256:03d08cea230e892e1b6cbfe523c19b568a834c5888aac5c789d1fb8d6ee93d96",
      },
    ],
  },
  {
    designId: "30357",
    connectorAuthority: "ldcad-shadow",
    studCount: 8,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-2x1.dat",
        sha256: "sha256:03d08cea230e892e1b6cbfe523c19b568a834c5888aac5c789d1fb8d6ee93d96",
      },
      {
        archiveId: "official",
        path: "p/stug-3x1.dat",
        sha256: "sha256:9ae441c03c2e73972a26d74f7ead4de280947397dc09e2fd9857ca73ec87181a",
      },
    ],
  },
  {
    designId: "2450",
    connectorAuthority: "ldcad-shadow",
    studCount: 6,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
      {
        archiveId: "official",
        path: "p/stug-2x2.dat",
        sha256: "sha256:16114159ea25719341a852d5403dc9982a6211f2fcb23f5c4c3eac05a2ad43f7",
      },
    ],
  },
  {
    designId: "79491",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "30503",
    connectorAuthority: "ldcad-shadow",
    studCount: 10,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
      {
        archiveId: "official",
        path: "p/stug-1x3.dat",
        sha256: "sha256:f24de368545aa96580b811daa6c25e18f5bfdbaca1d4b11addcfa7cbb625f4c9",
      },
    ],
  },
  {
    designId: "6106",
    connectorAuthority: "ldcad-shadow",
    studCount: 26,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
      {
        archiveId: "official",
        path: "p/stug-2x2.dat",
        sha256: "sha256:16114159ea25719341a852d5403dc9982a6211f2fcb23f5c4c3eac05a2ad43f7",
      },
    ],
  },
  {
    designId: "30565",
    connectorAuthority: "ldcad-shadow",
    studCount: 11,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "80015",
    connectorAuthority: "builder-connectivity",
    studCount: 5,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
      {
        archiveId: "official",
        path: "p/stug-2x1.dat",
        sha256: "sha256:03d08cea230e892e1b6cbfe523c19b568a834c5888aac5c789d1fb8d6ee93d96",
      },
    ],
  },
  {
    designId: "28802",
    connectorAuthority: "ldcad-shadow",
    studCount: 6,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-2x1.dat",
        sha256: "sha256:03d08cea230e892e1b6cbfe523c19b568a834c5888aac5c789d1fb8d6ee93d96",
      },
      {
        archiveId: "official",
        path: "p/stug2-4x1.dat",
        sha256: "sha256:179d252971d76f12196c7c2c3b6f89bb6c7eab21d9df9625f44a8064e49e4996",
      },
    ],
  },
  {
    designId: "11253",
    connectorAuthority: "ldcad-shadow",
    studCount: 1,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "15254",
    connectorAuthority: "builder",
    studCount: 6,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-1x6.dat",
        sha256: "sha256:907b74bad03688f6d2f22220db6ec4a6c922203a3e3001aa24f214c6ed48a226",
      },
    ],
  },
  {
    designId: "41682",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stug-2x1.dat",
        sha256: "sha256:03d08cea230e892e1b6cbfe523c19b568a834c5888aac5c789d1fb8d6ee93d96",
      },
    ],
  },
  {
    designId: "2877",
    connectorAuthority: "builder",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "3040",
    connectorAuthority: "builder",
    studCount: 1,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "32064",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud2.dat",
        sha256: "sha256:5ed3702c7d7000bfac2906f12b74ae312c59194a8e3b504952820c826b51c810",
      },
    ],
  },
  {
    designId: "11212",
    connectorAuthority: "ldcad-shadow",
    studCount: 9,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "33909",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "78329",
    connectorAuthority: "ldcad-shadow",
    studCount: 5,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "73230",
    connectorAuthority: "ldcad-shadow",
    studCount: 1,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud2.dat",
        sha256: "sha256:5ed3702c7d7000bfac2906f12b74ae312c59194a8e3b504952820c826b51c810",
      },
    ],
  },
  {
    designId: "3245c",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "2453b",
    connectorAuthority: "ldcad-shadow",
    studCount: 1,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "10201",
    connectorAuthority: "ldcad-shadow",
    studCount: 6,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
      {
        archiveId: "official",
        path: "p/stud2.dat",
        sha256: "sha256:5ed3702c7d7000bfac2906f12b74ae312c59194a8e3b504952820c826b51c810",
      },
    ],
  },
  {
    designId: "3245b",
    connectorAuthority: "ldcad-shadow",
    studCount: 2,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud.dat",
        sha256: "sha256:db037d518d7c08bcdc1f0e7497f4f98e97d99850531dd62d602965520f3bf8f4",
      },
    ],
  },
  {
    designId: "15573",
    connectorAuthority: "ldcad-shadow",
    studCount: 1,
    visibleStudSources: [
      {
        archiveId: "official",
        path: "p/stud2.dat",
        sha256: "sha256:5ed3702c7d7000bfac2906f12b74ae312c59194a8e3b504952820c826b51c810",
      },
    ],
  },
] as const;
