// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_I = [
  {
    designId: "15573",
    ldrawId: "15573.dat",
    family: "jumper-plate",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 8,
    meshAssetId: "ldraw:official:15573.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -4, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-4", "-20"],
      max: ["10", "4", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-8", "-20"],
      max: ["10", "4", "20"],
    },
    studsLdu: [[0, -4, 0, 6.0001514980873605, 4]],
    clutchesLdu: [
      [0, 4, -10],
      [0, 4, 0],
      [0, 4, 10],
    ],
    clutchPortSemantics: [
      {
        positionLdu: [0, 4, -10],
        id: "undersideClutch:0:0",
        sharedCapacityGroupIds: ["15573:negative-z-half"],
      },
      {
        positionLdu: [0, 4, 0],
        id: "undersideClutch:center",
        sharedCapacityGroupIds: ["15573:negative-z-half", "15573:positive-z-half"],
      },
      {
        positionLdu: [0, 4, 10],
        id: "undersideClutch:0:1",
        sharedCapacityGroupIds: ["15573:positive-z-half"],
      },
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -4, 7, 6, 0, 16, -6, -4, -3, 6, 0, 3, -6, -4, -16, 6, 0, -7, -4, -4, 6, 4, 0, 7, -4, -4, 3, 4, 0, 4, -4, -4, -4, 4, 0, -3, -4, -4, -7, 4, 0, -6, -3, -4, 4, 3, 0, 6, -3, -4, -6, 3, 0, -4, -10, -4, -20, -9, 3, 20, -9, -4, 19, 10, 3, 20, -9, -4, -20, 10, 3, -19, 9, -4, -19, 10, 3, 19, -9, -4, -19, -6, 4, 19, -6, -4, 16, 9, 4, 19, -6, -4, 3, -4, 4, 7, -6, -4, -7, -4, 4, -3, -6, -4, -19, 9, 4, -16, -4, -4, 4, -3, 4, 6, -4, -4, -6, -3, 4, -4, 3, -4, 4, 9, 4, 6, 3, -4, -6, 9, 4, -4, 4, -4, 6, 9, 4, 7, 4, -4, 3, 9, 4, 4, 4, -4, -4, 9, 4, -3, 4, -4, -7, 9, 4, -6, 6, -4, 7, 9, 4, 16, 6, -4, -3, 9, 4, 3, 6, -4, -16, 9, 4, -7],
    ldrawSource: {
      title: "Plate  1 x  2 with Groove with 1 Centre Stud, without Understud",
      author: "Magnus Forsberg [MagFors]",
      ldrawOrg: "Part UPDATE 2013-01",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:c6946965875a8275996c4559cd355ea13a20197e96f33585cd750bb1da89b56d",
      closureFileCount: 11,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud2.dat", "parts/15573.dat"],
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
