// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_H = [
  {
    designId: "3245c",
    ldrawId: "3245c.dat",
    catalogId: "builtin:brick-1x2x2-without-understud",
    displayName: "Brick 1 x 2 x 2 Without Understud",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    variant: "without-understud",
    heightLdu: 48,
    meshAssetId: "ldraw:official:3245c.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -24, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-24", "-20"],
      max: ["10", "24", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-28", "-20"],
      max: ["10", "24", "20"],
    },
    studsLdu: [
      [0, -24, -10, 6.0001514980873605, 4],
      [0, -24, 10, 6.0001514980873605, 4],
    ],
    clutchesLdu: [
      [0, 24, -10],
      [0, 24, 0],
      [0, 24, 10],
    ],
    clutchSharedCapacityGroupIds: [
      ["3245c:negative-z-half"],
      ["3245c:negative-z-half", "3245c:positive-z-half"],
      ["3245c:positive-z-half"],
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -24, 7, 6, -20, 16, -6, -24, -3, 6, -20, 3, -6, -24, -16, 6, -20, -7, -5, -24, 6, 5, -20, 7, -5, -24, 3, 5, -20, 4, -5, -24, -4, 5, -20, -3, -5, -24, -7, 5, -20, -6, -4, -24, 4, 4, -20, 6, -4, -24, -6, 4, -20, -4, -10, -24, -20, -6, 24, 20, -6, -24, 16, 10, 24, 20, -6, -24, 3, -5, 24, 7, -6, -24, -7, -5, 24, -3, -6, -24, -20, 10, 24, -16, -5, -24, 4, -4, 24, 6, -5, -24, -6, -4, 24, -4, 4, -24, 4, 10, 24, 6, 4, -24, -6, 10, 24, -4, 5, -24, 6, 10, 24, 7, 5, -24, 3, 10, 24, 4, 5, -24, -4, 10, 24, -3, 5, -24, -7, 10, 24, -6, 6, -24, 7, 10, 24, 16, 6, -24, -3, 10, 24, 3, 6, -24, -16, 10, 24, -7],
    ldrawSource: {
      title: "Brick  1 x  2 x  2 without Understud",
      author: "Stephan Meisinger [smr]",
      ldrawOrg: "Part UPDATE 2017-01",
      licenseExpression: "CC-BY-2.0 OR CC-BY-4.0",
      rootSha256: "sha256:9cc04bca1050e0b16a00c76a432f9cbb769655dc79188a0df3cffa2229dc6615",
      closureFileCount: 10,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud.dat", "parts/3245a.dat", "parts/3245c.dat", "parts/s/3245cs01.dat"],
    },
  },
  {
    designId: "2453b",
    ldrawId: "2453b.dat",
    catalogId: "builtin:brick-1x1x5-solid-stud",
    displayName: "Brick 1 x 1 x 5 with Solid Stud",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 1,
    variant: "solid-stud",
    heightLdu: 120,
    meshAssetId: "ldraw:official:2453b.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -60, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-60", "-10"],
      max: ["10", "60", "10"],
    },
    exactBoundsLdu: {
      min: ["-10", "-64", "-10"],
      max: ["10", "60", "10"],
    },
    studsLdu: [[0, -60, 0, 6.0001514980873605, 4]],
    clutchesLdu: [[0, 60, 0]],
    // prettier-ignore
    bodyBoxesLdu: [-6, -60, -6, 6, -56, 6, -10, -60, -10, 10, 60, -6, -10, -60, -6, -6, 60, 10, 6, -60, -6, 10, 60, 10, -6, -60, 6, 6, 60, 10],
    ldrawSource: {
      title: "Brick  1 x  1 x  5 with Solid Stud",
      author: "Merlijn Wissink [legolijntje]",
      ldrawOrg: "Part UPDATE 2025-09",
      licenseExpression: "CC-BY-2.0 OR CC-BY-4.0",
      rootSha256: "sha256:3c7caddd91a2467243cf3f3bd0bdd8ee8fa1cbd5435591a6491841ee1ca49b01",
      closureFileCount: 6,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud.dat", "parts/2453b.dat"],
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
