// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";
import { SET_6651557_MEASURED_BLUEPRINTS_G } from "./part-blueprints-6651557-measured-g.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_F = [
  {
    designId: "4519",
    ldrawId: "4519.dat",
    catalogId: "builtin:axle-1x3",
    displayName: "Technic Axle 3",
    family: "axle",
    widthStuds: 1,
    lengthStuds: 3,
    heightLdu: 12,
    meshAssetId: "ldraw:official:4519.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, 0, 0] },
    connectorGridCenterLdu: [0, 0],
    exactBodyBoundsLdu: {
      min: ["-29.5", "-6", "-6"],
      max: ["29.5", "6", "6"],
    },
    exactBoundsLdu: {
      min: ["-29.5", "-6", "-6"],
      max: ["29.5", "6", "6"],
    },
    studsLdu: [],
    clutchesLdu: [],
    sourceConnectorsLdu: [
      {
        kind: "axle",
        positionLdu: [-20, 0, 0],
        normal: [-1, 0, 0],
      },
      {
        kind: "axle",
        positionLdu: [0, 0, 0],
        normal: [1, 0, 0],
      },
      {
        kind: "axle",
        positionLdu: [20, 0, 0],
        normal: [1, 0, 0],
      },
    ],
    // prettier-ignore
    bodyBoxesLdu: [-28, -6, -1, 28, 6, 1, -28, -5.80115, -2, 28, 5.80115, -1, -28, -5.80115, 1, 28, 5.80115, 2, -29, -5.744201669, -1, -28, 5.744201669, 1, 28, -5.744201669, -1, 29, 5.744201669, 1, -29, -5.545351669, -2, -28, 5.545351669, -1, 28, -5.545351669, -2, 29, 5.545351669, -1, -29, -5.545351669, 1, -28, 5.545351669, 2, 28, -5.545351669, 1, 29, 5.545351669, 2, -29.5, -4.97476463, -1, -29, 4.97476463, 1, 29, -4.97476463, -1, 29.5, 4.97476463, 1, -29.5, -4.775881125, -2, -29, 4.775881125, -1, 29, -4.775881125, -2, 29.5, 4.775881125, -1, -29.5, -4.775881125, 1, -29, 4.775881125, 2, 29, -4.775881125, 1, 29.5, 4.775881125, 2, -28, -2, -6, 28, 2, -2, -28, -2, 2, 28, 2, 6, -29, -1.956652092, -3, -28, 1.956652092, -2, 28, -1.956652092, -3, 29, 1.956652092, -2, -29, -1.956652092, 2, -28, 1.956652092, 3, 28, -1.956652092, 2, 29, 1.956652092, 3, -29, -1.8712828, -4, -28, 1.8712828, -3, 28, -1.8712828, -4, 29, 1.8712828, -3, -29, -1.8712828, 3, -28, 1.8712828, 4, 28, -1.8712828, 3, 29, 1.8712828, 4, -29.5, -1.869956277, -3, -29, 1.869956277, -2, 29, -1.869956277, -3, 29.5, 1.869956277, -2, -29.5, -1.869956277, 2, -29, 1.869956277, 3, 29, -1.869956277, 2, 29.5, 1.869956277, 3, -29, -1.869219347, -6, -28, 1.869219347, -4, 28, -1.869219347, -6, 29, 1.869219347, -4, -29, -1.869219347, 4, -28, 1.869219347, 6, 28, -1.869219347, 4, 29, 1.869219347, 6, -29.5, -1.708057784, -4, -29, 1.708057784, -3, 29, -1.708057784, -4, 29.5, 1.708057784, -3, -29.5, -1.708057784, 3, -29, 1.708057784, 4, 29, -1.708057784, 3, 29.5, 1.708057784, 4, -29.5, -1.660953092, -5, -29, 1.660953092, -4, 29, -1.660953092, -5, 29.5, 1.660953092, -4, -29.5, -1.660953092, 4, -29, 1.660953092, 5, 29, -1.660953092, 4, 29.5, 1.660953092, 5],
    ldrawSource: {
      title: "Technic Axle  3",
      author: "James Jessiman",
      ldrawOrg: "Part UPDATE 2025-09",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:ecec609013e9d7af63c352cb61d990077c005c4c5453e121b3d192914ab55ff0",
      closureFileCount: 4,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["parts/4519.dat"],
    },
  },
  ...SET_6651557_MEASURED_BLUEPRINTS_G,
] as const satisfies readonly MeasuredPartBlueprint[];
