// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_G = [
  {
    designId: "32064",
    ldrawId: "32064.dat",
    catalogId: "builtin:technic-brick-1x2-axle-hole",
    displayName: "Technic Brick 1 x 2 with Axle Hole",
    family: "technic-brick",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 24,
    meshAssetId: "ldraw:official:32064.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0] },
    connectorGridCenterLdu: [0, 0],
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-20"],
      max: ["10", "12", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-16", "-20"],
      max: ["10", "12", "20"],
    },
    studsLdu: [
      [0, -12, -10, 6.0001514980873605, 4],
      [0, -12, 10, 6.0001514980873605, 4],
    ],
    clutchesLdu: [
      [0, 12, -10],
      [0, 12, 10],
    ],
    sourceConnectorsLdu: [
      {
        kind: "axleHole",
        positionLdu: [0, -2, 0],
        normal: [1, 0, 0],
      },
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -12, 6, 6, -8, 16, -6, -12, -16, 6, -8, -6, -3, -12, 5, 3, 4.0957464859999995, 6, -3, -12, -6, 3, 4.0957464859999995, -5, -3, -12, 4, 3, 4.764057213000001, 5, -3, -12, -5, 3, 4.764057213000001, -4, -3, -12, 3, 3, 5.403449176999999, 4, -3, -12, -4, 3, 5.403449176999999, -3, -6, -12, 2, 6, 5.602299451, 3, -6, -12, -3, 6, 5.602299451, -2, -6, -12, 1, 6, 5.8011497259999985, 2, -6, -12, -2, 6, 5.8011497259999985, -1, -6, -12, -1, 6, 6, 1, -10, -12, -20, -6, 12, 20, -6, -12, 16, 10, 12, 20, -6, -12, 3, -3, 12, 6, -6, -12, -6, -3, 12, -3, -6, -12, -20, 10, 12, -16, 3, -12, 3, 10, 12, 6, 3, -12, -6, 10, 12, -3, 6, -12, 6, 10, 12, 16, 6, -12, -3, 10, 12, 3, 6, -12, -16, 10, 12, -6],
    ldrawSource: {
      title: "~Moved to 32064a",
      author: "[PTadmin]",
      ldrawOrg: "Part UPDATE 2009-03",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:b6240d5798083701834cec8f566d7fca05cbc51123fad8500d3125fa68b4c465",
      closureFileCount: 23,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/axlehol5.dat", "p/stud2.dat", "parts/32064a.dat"],
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
