// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae). These render-only declarations consume only that pinned
// official archive and no other evidence source. Do not hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { RenderOnlyPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_RENDER_ONLY_BLUEPRINTS = [
  {
    designId: "41770a",
    ldrawId: "41770a.dat",
    family: "wedge-plate",
    widthStuds: 2,
    lengthStuds: 4,
    variant: "left",
    heightLdu: 8,
    meshAssetId: "ldraw:official:41770a.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0] },
    exactBodyBoundsLdu: {
      min: ["-20", "-4", "-40"],
      max: ["20", "4", "40"],
    },
    exactBoundsLdu: {
      min: ["-20", "-8", "-40"],
      max: ["20", "4", "40"],
    },
    sourceStudSeatsLdu: [
      [-10, -4, -30],
      [-10, -4, -10],
      [-10, -4, 10],
      [-10, -4, 30],
    ],
    ldrawSource: {
      title: "Wing  2 x  4 Left without Chamfer",
      author: "Takeshi Takahashi [RainbowDolphin]",
      ldrawOrg: "Part UPDATE 2026-05",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:59648c2ca07a51d82fdc9aabf4edb65f4942760dc9df3b64946d13fd82b0303d",
      closureFileCount: 39,
    },
  },
  {
    designId: "41769a",
    ldrawId: "41769a.dat",
    family: "wedge-plate",
    widthStuds: 2,
    lengthStuds: 4,
    variant: "right",
    heightLdu: 8,
    meshAssetId: "ldraw:official:41769a.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0] },
    exactBodyBoundsLdu: {
      min: ["-20", "-4", "-40"],
      max: ["20", "4", "40"],
    },
    exactBoundsLdu: {
      min: ["-20", "-8", "-40"],
      max: ["20", "4", "40"],
    },
    sourceStudSeatsLdu: [
      [10, -4, -30],
      [10, -4, -10],
      [10, -4, 10],
      [10, -4, 30],
    ],
    ldrawSource: {
      title: "Wing  2 x  4 Right without Chamfer",
      author: "Takeshi Takahashi [RainbowDolphin]",
      ldrawOrg: "Part UPDATE 2026-05",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:0b069ab042f2cc8297a52e76b49a06e504cd4e9a51f02d6aea8c63f686c28ff8",
      closureFileCount: 39,
    },
  },
  {
    designId: "43723a",
    ldrawId: "43723a.dat",
    family: "wedge-plate",
    widthStuds: 2,
    lengthStuds: 3,
    variant: "left",
    heightLdu: 8,
    meshAssetId: "ldraw:official:43723a.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0] },
    exactBodyBoundsLdu: {
      min: ["-20", "-4", "-30"],
      max: ["20", "4", "30"],
    },
    exactBoundsLdu: {
      min: ["-20", "-8", "-30"],
      max: ["20", "4", "30"],
    },
    sourceStudSeatsLdu: [
      [-10, -4, -20],
      [-10, -4, 0],
      [-10, -4, 20],
    ],
    ldrawSource: {
      title: "Wing  2 x  3 Left without Chamfer",
      author: "Donald Sutter [technog]",
      ldrawOrg: "Part UPDATE 2026-05",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:27225adfc6ffa1e36ae9a1a9448fada822a6f3e43c996c5512f5b2d6be24f181",
      closureFileCount: 31,
    },
  },
  {
    designId: "43722a",
    ldrawId: "43722a.dat",
    family: "wedge-plate",
    widthStuds: 2,
    lengthStuds: 3,
    variant: "right",
    heightLdu: 8,
    meshAssetId: "ldraw:official:43722a.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0] },
    exactBodyBoundsLdu: {
      min: ["-20", "-4", "-30"],
      max: ["20", "4", "30"],
    },
    exactBoundsLdu: {
      min: ["-20", "-8", "-30"],
      max: ["20", "4", "30"],
    },
    sourceStudSeatsLdu: [
      [10, -4, -20],
      [10, -4, 0],
      [10, -4, 20],
    ],
    ldrawSource: {
      title: "Wing  2 x  3 Right without Chamfer",
      author: "Donald Sutter [technog]",
      ldrawOrg: "Part UPDATE 2026-05",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:cb9c4cfc5c9254fab8191a085ed77d170e16d6f90647bac2c36ce666c1764f59",
      closureFileCount: 31,
    },
  },
  {
    designId: "54383",
    ldrawId: "54383.dat",
    family: "wedge-plate",
    widthStuds: 3,
    lengthStuds: 6,
    variant: "right",
    heightLdu: 8,
    meshAssetId: "ldraw:official:54383.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -4, 0] },
    exactBodyBoundsLdu: {
      min: ["-29", "-4", "-60"],
      max: ["30", "4", "60"],
    },
    exactBoundsLdu: {
      min: ["-29", "-8", "-60"],
      max: ["30", "4", "60"],
    },
    sourceStudSeatsLdu: [
      [0, -4, 10],
      [0, -4, 30],
      [0, -4, 50],
      [20, -4, -50],
      [20, -4, -30],
      [20, -4, -10],
      [20, -4, 10],
      [20, -4, 30],
      [20, -4, 50],
    ],
    ldrawSource: {
      title: "Wing  3 x  6 Right",
      author: "Magnus Forsberg [MagFors]",
      ldrawOrg: "Part UPDATE 2026-04",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:5c8d2a4649d0229388af615afc9e954d27844009156404fd546a97efe7655bfc",
      closureFileCount: 41,
    },
  },
  {
    designId: "3659",
    ldrawId: "3659.dat",
    family: "arch",
    widthStuds: 1,
    lengthStuds: 4,
    heightLdu: 24,
    meshAssetId: "ldraw:official:3659.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-40"],
      max: ["10", "12", "40"],
    },
    exactBoundsLdu: {
      min: ["-10", "-16", "-40"],
      max: ["10", "12", "40"],
    },
    sourceStudSeatsLdu: [
      [0, -12, -30],
      [0, -12, -10],
      [0, -12, 10],
      [0, -12, 30],
    ],
    ldrawSource: {
      title: "Arch  1 x  4",
      author: "James Jessiman",
      ldrawOrg: "Part UPDATE 2010-03",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:7544bbc1fae27eb339ee29a72900d411ade577a78a1686227af32ac0efce150c",
      closureFileCount: 10,
    },
  },
  {
    designId: "3455",
    ldrawId: "3455.dat",
    family: "arch",
    widthStuds: 1,
    lengthStuds: 6,
    heightLdu: 24,
    meshAssetId: "ldraw:official:3455.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-60"],
      max: ["10", "12", "60"],
    },
    exactBoundsLdu: {
      min: ["-10", "-16", "-60"],
      max: ["10", "12", "60"],
    },
    sourceStudSeatsLdu: [
      [0, -12, -50],
      [0, -12, -30],
      [0, -12, -10],
      [0, -12, 10],
      [0, -12, 30],
      [0, -12, 50],
    ],
    ldrawSource: {
      title: "Arch  1 x  6",
      author: "James Jessiman",
      ldrawOrg: "Part UPDATE 2005-01",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:6e8fcdca71b4dd1a875b926ed5b28889fc4a47a01272b6550987338f0619083b",
      closureFileCount: 7,
    },
  },
  {
    designId: "11477",
    ldrawId: "11477.dat",
    family: "curved-slope",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 16,
    meshAssetId: "ldraw:official:11477.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, 8, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-8.00006098", "-20"],
      max: ["10", "8", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-8.00006098", "-20"],
      max: ["10", "8", "20"],
    },
    sourceStudSeatsLdu: [],
    ldrawSource: {
      title: "Slope Brick Curved  2 x  1",
      author: "Owen Burgoyne [C3POwen]",
      ldrawOrg: "Part UPDATE 2013-01",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:fed74af9f56bcb149a7f67af4b427c261b41d24d15ed7a3466e24170377a0ba6",
      closureFileCount: 16,
    },
  },
  {
    designId: "50950",
    ldrawId: "50950.dat",
    family: "curved-slope",
    widthStuds: 1,
    lengthStuds: 3,
    heightLdu: 24,
    meshAssetId: "ldraw:official:50950.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -12, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-30"],
      max: ["10", "12", "30"],
    },
    exactBoundsLdu: {
      min: ["-10", "-12", "-30"],
      max: ["10", "12", "30"],
    },
    sourceStudSeatsLdu: [],
    ldrawSource: {
      title: "Slope Brick Curved  3 x  1",
      author: "Orion Pobursky [OrionP]",
      ldrawOrg: "Part UPDATE 2026-06",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:95ce8c0315699aa02e600e36a9fed48f991e95974c536ede259caa5c12c7dd9d",
      closureFileCount: 13,
    },
  },
  {
    designId: "61678",
    ldrawId: "61678.dat",
    family: "curved-slope",
    widthStuds: 1,
    lengthStuds: 4,
    heightLdu: 24,
    meshAssetId: "ldraw:official:61678.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -12, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-40"],
      max: ["10", "12", "40"],
    },
    exactBoundsLdu: {
      min: ["-10", "-12", "-40"],
      max: ["10", "12", "40"],
    },
    sourceStudSeatsLdu: [],
    ldrawSource: {
      title: "Slope Brick Curved  4 x  1",
      author: "Tim Gould [timgould]",
      ldrawOrg: "Part UPDATE 2014-01",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:e06daaca0499570e65d18b3e969be2e7be66896e0735b829c579bfcb6caa1eb8",
      closureFileCount: 12,
    },
  },
  {
    designId: "54200",
    ldrawId: "54200.dat",
    family: "cheese-slope",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 16,
    meshAssetId: "ldraw:official:54200.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, 8, 0] },
    exactBodyBoundsLdu: {
      min: ["-10", "-7.6", "-10"],
      max: ["10", "8", "10"],
    },
    exactBoundsLdu: {
      min: ["-10", "-7.6", "-10"],
      max: ["10", "8", "10"],
    },
    sourceStudSeatsLdu: [],
    ldrawSource: {
      title: "Slope Brick 31  1 x  1 x  0.667",
      author: "Orion Pobursky [OrionP]",
      ldrawOrg: "Part UPDATE 2022-04",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:3f0c25da3dac0600209a032c53c040b8668e617374997546d5449528eb7099c9",
      closureFileCount: 5,
    },
  },
  {
    designId: "85984",
    ldrawId: "85984.dat",
    family: "cheese-slope",
    widthStuds: 2,
    lengthStuds: 1,
    heightLdu: 16,
    meshAssetId: "ldraw:official:85984.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, 8, 0] },
    exactBodyBoundsLdu: {
      min: ["-20", "-7.6", "-10"],
      max: ["20", "8", "10"],
    },
    exactBoundsLdu: {
      min: ["-20", "-7.6", "-10"],
      max: ["20", "8", "10"],
    },
    sourceStudSeatsLdu: [],
    ldrawSource: {
      title: "Slope Brick 31  1 x  2 x  0.667",
      author: "Magnus Forsberg [MagFors]",
      ldrawOrg: "Part UPDATE 2020-02",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:4ec471415207722114f48abb384626d3dbda59796803cafc7feaf824ed88d426",
      closureFileCount: 10,
    },
  },
] as const satisfies readonly RenderOnlyPartBlueprint[];
