// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_E = [
  {
    designId: "3040",
    ldrawId: "3040.dat",
    catalogId: "builtin:slope-1x2-45",
    displayName: "Slope 45 1 x 2",
    family: "slope",
    widthStuds: 1,
    lengthStuds: 2,
    variant: "45",
    heightLdu: 24,
    meshAssetId: "ldraw:official:3040.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -12, 10] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-20"],
      max: ["10", "12", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-16", "-20"],
      max: ["10", "12", "20"],
    },
    studsLdu: [[0, -12, 10, 6.0001514980873605, 4]],
    clutchesLdu: [
      [0, 12, -10],
      [0, 12, 10],
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -12, 0, -4, -8, 16, 4, -12, 0, 6, -8, 16, -4, -12, 3, -3, -8, 16, 3, -12, 3, 4, -8, 16, -3, -12, 4, 3, -8, 16, -6, -12, -1, -4, -7, 0, 4, -12, -1, 6, -7, 0, -10, -12, -1, -6, 12, 20, -4, -12, -1, 4, 12, 3, 6, -12, -1, 10, 12, 20, -3, -12, 3, 3, 12, 4, -6, -12, 16, 6, 12, 20, -6, -11, -2, -4, -6, -1, 4, -11, -2, 6, -6, -1, -10, -11, -2, -6, 12, -1, -4, -11, -2, 4, 12, -1, 6, -11, -2, 10, 12, -1, -6, -10, -3, -4, -5, -2, 4, -10, -3, 6, -5, -2, -10, -10, -3, -6, 12, -2, -4, -10, -3, 4, 12, -2, 6, -10, -3, 10, 12, -2, -6, -9, -4, -3, -4, -3, 3, -9, -4, 6, -4, -3, -10, -9, -4, -6, 12, -3, -3, -9, -4, 3, 12, -3, 6, -9, -4, 10, 12, -3, -6, -8, -5, 6, -3, -4, -10, -8, -5, -6, 12, -4, 6, -8, -5, 10, 12, -4, -6, -7, -6, 6, -2, -5, -10, -7, -6, -6, 12, -5, 6, -7, -6, 10, 12, -5, -6, -6, -7, 6, -1, -6, -10, -6, -7, -6, 12, -6, 6, -6, -7, 10, 12, -6, -6, -5, -8, 6, 0, -7, -10, -5, -8, -6, 12, -7, 6, -5, -8, 10, 12, -7, -6, -4, -9, 6, 1, -8, -10, -4, -9, -6, 12, -8, 6, -4, -9, 10, 12, -8, -6, -3, -10, 6, 2, -9, -10, -3, -10, -6, 12, -9, 6, -3, -10, 10, 12, -9, -6, -2, -11, 6, 3, -10, -10, -2, -11, -6, 12, -10, 6, -2, -11, 10, 12, -10, -6, -1, -12, 6, 4, -11, -10, -1, -12, -6, 12, -11, 6, -1, -12, 10, 12, -11, -6, 0, -13, 6, 5, -12, -10, 0, -13, -6, 12, -12, 6, 0, -13, 10, 12, -12, -6, 1, -14, 6, 6, -13, -10, 1, -14, -6, 12, -13, 6, 1, -14, 10, 12, -13, -6, 2, -15, 6, 7, -14, -10, 2, -15, -6, 12, -14, 6, 2, -15, 10, 12, -14, -6, 3, -16, 6, 8, -15, -10, 3, -16, -6, 12, -15, 6, 3, -16, 10, 12, -15, -10, 4, -17, 10, 12, -16, -10, 5, -18, 10, 12, -17, -10, 6, -19, 10, 12, -18, -10, 7, -20, 10, 12, -19],
    ldrawSource: {
      title: "~Moved to 3040b",
      author: "[PTadmin]",
      ldrawOrg: "Part UPDATE 2004-04",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:12c4aaf0642dc49397b2f269a64c9298f1650fce51a97d463f910f81a9d8068e",
      closureFileCount: 11,
    },
    builderSource: {
      revision: "F",
      recordSha256: "sha256:63ab72a4ff3b2d85b58af6586a1592124ab42019a84cb5faef137ee699836b28",
      frameSha256: "sha256:65d6be01240cad2790e9fb54fabb056b99c232c26736b33b7340f8a85511a4bf",
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
