// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_H = [
  {
    designId: "3245c",
    ldrawId: "3245c.dat",
    catalogId: "builtin:brick-1x2x2-without-understud",
    displayName: "Brick 1 x 2 x 2 Without Understud",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    variant: "without-understud",
    heightLdu: 48,
    meshAssetId: "ldraw:official:3245c.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -24, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-24", "-20"],
      max: ["10", "24", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-28", "-20"],
      max: ["10", "24", "20"],
    },
    studsLdu: [
      [0, -24, -10, 6.0001514980873605, 4],
      [0, -24, 10, 6.0001514980873605, 4],
    ],
    clutchesLdu: [
      [0, 24, -10],
      [0, 24, 0],
      [0, 24, 10],
    ],
    clutchSharedCapacityGroupIds: [
      ["3245c:negative-z-half"],
      ["3245c:negative-z-half", "3245c:positive-z-half"],
      ["3245c:positive-z-half"],
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -24, 7, 6, -20, 16, -6, -24, -3, 6, -20, 3, -6, -24, -16, 6, -20, -7, -5, -24, 6, 5, -20, 7, -5, -24, 3, 5, -20, 4, -5, -24, -4, 5, -20, -3, -5, -24, -7, 5, -20, -6, -4, -24, 4, 4, -20, 6, -4, -24, -6, 4, -20, -4, -10, -24, -20, -6, 24, 20, -6, -24, 16, 10, 24, 20, -6, -24, 3, -5, 24, 7, -6, -24, -7, -5, 24, -3, -6, -24, -20, 10, 24, -16, -5, -24, 4, -4, 24, 6, -5, -24, -6, -4, 24, -4, 4, -24, 4, 10, 24, 6, 4, -24, -6, 10, 24, -4, 5, -24, 6, 10, 24, 7, 5, -24, 3, 10, 24, 4, 5, -24, -4, 10, 24, -3, 5, -24, -7, 10, 24, -6, 6, -24, 7, 10, 24, 16, 6, -24, -3, 10, 24, 3, 6, -24, -16, 10, 24, -7],
    ldrawSource: {
      title: "Brick  1 x  2 x  2 without Understud",
      author: "Stephan Meisinger [smr]",
      ldrawOrg: "Part UPDATE 2017-01",
      licenseExpression: "CC-BY-2.0 OR CC-BY-4.0",
      rootSha256: "sha256:9cc04bca1050e0b16a00c76a432f9cbb769655dc79188a0df3cffa2229dc6615",
      closureFileCount: 10,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud.dat", "parts/3245a.dat", "parts/3245c.dat", "parts/s/3245cs01.dat"],
    },
  },
  {
    designId: "2453b",
    ldrawId: "2453b.dat",
    catalogId: "builtin:brick-1x1x5-solid-stud",
    displayName: "Brick 1 x 1 x 5 with Solid Stud",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 1,
    variant: "solid-stud",
    heightLdu: 120,
    meshAssetId: "ldraw:official:2453b.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -60, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-60", "-10"],
      max: ["10", "60", "10"],
    },
    exactBoundsLdu: {
      min: ["-10", "-64", "-10"],
      max: ["10", "60", "10"],
    },
    studsLdu: [[0, -60, 0, 6.0001514980873605, 4]],
    clutchesLdu: [[0, 60, 0]],
    // prettier-ignore
    bodyBoxesLdu: [-6, -60, -6, 6, -56, 6, -10, -60, -10, 10, 60, -6, -10, -60, -6, -6, 60, 10, 6, -60, -6, 10, 60, 10, -6, -60, 6, 6, 60, 10],
    ldrawSource: {
      title: "Brick  1 x  1 x  5 with Solid Stud",
      author: "Merlijn Wissink [legolijntje]",
      ldrawOrg: "Part UPDATE 2025-09",
      licenseExpression: "CC-BY-2.0 OR CC-BY-4.0",
      rootSha256: "sha256:3c7caddd91a2467243cf3f3bd0bdd8ee8fa1cbd5435591a6491841ee1ca49b01",
      closureFileCount: 6,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud.dat", "parts/2453b.dat"],
    },
  },
  {
    designId: "10201",
    ldrawId: "10201.dat",
    catalogId: "builtin:bracket-1x2-1x4-rounded-corners",
    displayName: "Bracket 1 x 2 - 1 x 4 with Rounded Corners",
    family: "bracket",
    widthStuds: 4,
    lengthStuds: 1,
    variant: "rounded-corners",
    heightLdu: 20,
    meshAssetId: "ldraw:official:10201.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-0", translationLdu: [0, -10, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-40", "-10", "-14"],
      max: ["40", "10", "10"],
    },
    exactBoundsLdu: {
      min: ["-40", "-14", "-18"],
      max: ["40", "10", "10"],
    },
    studsLdu: [
      [-30, 0, -14, 6.0001514980873605, 4, 0, 0, -1],
      [-10, -10, 0, 6.0001514980873605, 4],
      [-10, 0, -14, 6.0001514980873605, 4, 0, 0, -1],
      [10, -10, 0, 6.0001514980873605, 4],
      [10, 0, -14, 6.0001514980873605, 4, 0, 0, -1],
      [30, 0, -14, 6.0001514980873605, 4, 0, 0, -1],
    ],
    clutchesLdu: [
      [-10, -2, 0],
      [10, -2, 0],
    ],
    // prettier-ignore
    bodyBoxesLdu: [-16, -10, -10, -12, -6, 6, -8, -10, -10, 8, -6, -4, 12, -10, -10, 16, -6, 6, -12, -10, -6, -8, -6, 6, 8, -10, -6, 12, -6, 6, -8, -10, -4, -3, -6, -3, 3, -10, -4, 8, -6, -3, -8, -10, -3, -4, -6, 6, 4, -10, -3, 8, -6, 6, -4, -10, 3, -3, -6, 6, 3, -10, 3, 4, -6, 6, -3, -10, 4, 3, -6, 6, -20, -10, -10, -16, -2, 10, -12, -10, -10, -8, -2, -6, 8, -10, -10, 12, -2, -6, 16, -10, -10, 20, -2, 10, -3, -10, -4, 3, -2, 4, -4, -10, -3, -3, -2, 3, 3, -10, -3, 4, -2, 3, -16, -10, 6, 16, -2, 10, -39, -10, -14, 39, 10, -10, -40, -9.691014303, -14, -39, 9.691014303, -10, 39, -9.691014303, -14, 40, 9.691014303, -10],
    ldrawSource: {
      title: "=Bracket  1 x  2 -  1 x  4 with Rounded Corners",
      author: "Chris Dee [cwdee]",
      ldrawOrg: "Part Alias UPDATE 2014-02",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:028bc441268df93c08a363d375406cdf1eb70a25250bb3b56945fd6828395b7e",
      closureFileCount: 21,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: [
        "p/stud.dat",
        "p/stud2.dat",
        "p/stud3.dat",
        "parts/2436a.dat",
        "parts/2436b.dat",
      ],
    },
  },
  {
    designId: "3245b",
    ldrawId: "3245b.dat",
    catalogId: "builtin:brick-1x2x2-inside-axle-holder",
    displayName: "Brick 1 x 2 x 2 with Inside Axle Holder",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    variant: "inside-axle-holder",
    heightLdu: 48,
    meshAssetId: "ldraw:official:3245b.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -24, 0] },
    connectorGridCenterLdu: [0, 0],
    validatedConnectionStudProfile: "nominal-stud-tube/1",
    exactBodyBoundsLdu: {
      min: ["-10", "-24", "-20"],
      max: ["10", "24", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-28", "-20"],
      max: ["10", "24", "20"],
    },
    studsLdu: [
      [0, -24, -10, 6.0001514980873605, 4],
      [0, -24, 10, 6.0001514980873605, 4],
    ],
    clutchesLdu: [
      [0, 24, -10],
      [0, 24, 10],
    ],
    sourceConnectorsLdu: [
      {
        kind: "blindAxleHole",
        positionLdu: [0, 2, 0],
        normal: [0, 1, 0],
        axialSpan: {
          schemaVersion: "connector-axial-span/1",
          openEndLdu: [0, 24, 0],
          closedEndLdu: [0, -20, 0],
          depthLdu: 44,
          sliding: false,
        },
      },
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -24, 5, 6, -20, 16, -6, -24, -2, 6, -20, 2, -6, -24, -16, 6, -20, -5, -4, -24, 4, 4, -20, 5, -4, -24, -5, 4, -20, -4, -3, -24, 3, 3, -20, 4, -3, -24, -4, 3, -20, -3, -2, -24, 2, 2, -20, 3, -2, -24, -3, 2, -20, -2, -3, -24, 2, -2, 20.75, 3, -3, -24, -3, -2, 20.75, -2, 2, -24, 2, 3, 20.75, 3, 2, -24, -3, 3, 20.75, -2, -4, -24, 2, -3, 21.5, 4, -4, -24, -4, -3, 21.5, -2, 3, -24, 2, 4, 21.5, 4, 3, -24, -4, 4, 21.5, -2, -5, -24, 2, -4, 22.25, 5, -5, -24, -5, -4, 22.25, -2, 4, -24, 2, 5, 22.25, 5, 4, -24, -5, 5, 22.25, -2, -6, -24, 2, -5, 23, 5, -6, -24, -5, -5, 23, -2, 5, -24, 2, 6, 23, 5, 5, -24, -5, 6, 23, -2, -10, -24, -20, -6, 24, 20, -6, -24, 16, 10, 24, 20, -6, -24, -20, 10, 24, -16, 6, -24, -16, 10, 24, 16],
    ldrawSource: {
      title: "Brick  1 x  2 x  2 with Inside Axle Holder",
      author: "Steve Bliss [sbliss]",
      ldrawOrg: "Part UPDATE 2020-03",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:3741551acda207402f56b5f7905f1ccc507f8261ea92359fec7829b464b08649",
      closureFileCount: 11,
    },
    ldcadShadowSource: {
      libraryId: "ldcad-shadow-library",
      commit: "15aa1e718b6a8da37d24fc7af5e52e262c041bfb",
      manifestSha256: "sha256:668bc047a45e5560ff0fbbd69e9eb5adafab127781720bcb069a1554cb3f0c0f",
      compositionId: "ldcad-shadow-composed-over-ldraw-tree/1",
      shadowFiles: ["p/stud.dat", "parts/3245b.dat", "parts/s/3245bs02.dat"],
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
