// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// 6009f2e94204c4d3a63a4c812010b5c90bad8c5acb19b882c859fdac63734eae), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \
//     --official <ldraw-complete-2026-07.zip> \
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \
//     --shadow <ldcad-shadow-20260802> \
//     --pilot <set-6651557-source-pilot.json> \
//     --builder-frame <set-6651557-builder-ldraw-frame.json>

import type { MeasuredPartBlueprint } from "./measured-part-types.ts";

export const SET_6651557_MEASURED_BLUEPRINTS_D = [
  {
    designId: "2877",
    ldrawId: "2877.dat",
    catalogId: "builtin:brick-1x2-grille",
    displayName: "Brick 1 x 2 with Grille",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    variant: "grille",
    heightLdu: 24,
    meshAssetId: "ldraw:official:2877.dat",
    // prettier-ignore
    assetToCatalogFrame: { schemaVersion: "mesh-asset-to-catalog-frame/1", orientationId: "upright-yaw-90", translationLdu: [0, -12, 0] },
    connectorGridCenterLdu: [0, 0],
    exactBodyBoundsLdu: {
      min: ["-10", "-12", "-20"],
      max: ["10", "12", "20"],
    },
    exactBoundsLdu: {
      min: ["-10", "-16", "-20"],
      max: ["10", "12", "20"],
    },
    studsLdu: [
      [0, -12, -10, 6.0001514980873605, 4],
      [0, -12, 10, 6.0001514980873605, 4],
    ],
    clutchesLdu: [
      [0, 12, -10],
      [0, 12, 10],
    ],
    // prettier-ignore
    bodyBoxesLdu: [-6, -12, -16, -4, -8, 16, -4, -12, 3, -3, -8, 16, -4, -12, -16, -3, -8, -3, -3, -12, 4, 6, -8, 16, -3, -12, -16, 6, -8, -4, 3, -12, 3, 6, -8, 4, 3, -12, -4, 6, -8, -3, 4, -12, -3, 6, -8, 3, -9, -12, -20, -6, 12, 20, -6, -12, 16, 9, 12, 20, -6, -12, -20, 9, 12, -16, -4, -12, -3, 4, 12, 3, -3, -12, 3, 3, 12, 4, -3, -12, -4, 3, 12, -3, 6, -12, -16, 9, 12, 16, 9, -12, 17, 10, 12, 19, 9, -12, 13, 10, 12, 15, 9, -12, 9, 10, 12, 11, 9, -12, 5, 10, 12, 7, 9, -12, 1, 10, 12, 3, 9, -12, -3, 10, 12, -1, 9, -12, -7, 10, 12, -5, 9, -12, -11, 10, 12, -9, 9, -12, -15, 10, 12, -13, 9, -12, -19, 10, 12, -17, -10, -11, -20, -9, 11, 20],
    ldrawSource: {
      title: "Brick  1 x  2 with Grille",
      author: "James Jessiman",
      ldrawOrg: "Part UPDATE 2003-03",
      licenseExpression: "CC-BY-4.0",
      rootSha256: "sha256:46c3a0dc6329d3f0be9b3b4485b5e2e41295bad750a0f4c4b6a2e6631c0c0029",
      closureFileCount: 7,
    },
    builderSource: {
      revision: "E",
      recordSha256: "sha256:10259d71b0993d4131d2267fcd9247a20f8593bb542a1d1eee36ad4041f029b8",
      frameSha256: "sha256:234d34ebbabe20f9d2a4b351b31ed2922356b63c7a0bd01203b2bb22ccbff78d",
    },
  },
] as const satisfies readonly MeasuredPartBlueprint[];
