// Generated by scripts/generate-proper-orientation-tables.mjs. Do not edit.
import type { ProperOrientation } from "./types.ts";

/** The 20 non-upright members; constants.ts prepends the four legacy upright rows. */
export const GENERATED_NON_UPRIGHT_PROPER_ORIENTATIONS: readonly ProperOrientation[] =
  Object.freeze([
    Object.freeze({
      id: "proper-m-00n0n0n00",
      matrix: Object.freeze([0, 0, -1, 0, -1, 0, -1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-00nn000p0",
      matrix: Object.freeze([0, 0, -1, -1, 0, 0, 0, 1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-00np000n0",
      matrix: Object.freeze([0, 0, -1, 1, 0, 0, 0, -1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-00p0n0p00",
      matrix: Object.freeze([0, 0, 1, 0, -1, 0, 1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-00pn000n0",
      matrix: Object.freeze([0, 0, 1, -1, 0, 0, 0, -1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-00pp000p0",
      matrix: Object.freeze([0, 0, 1, 1, 0, 0, 0, 1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-0n000np00",
      matrix: Object.freeze([0, -1, 0, 0, 0, -1, 1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-0n000pn00",
      matrix: Object.freeze([0, -1, 0, 0, 0, 1, -1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-0n0n0000n",
      matrix: Object.freeze([0, -1, 0, -1, 0, 0, 0, 0, -1] as const),
    }),
    Object.freeze({
      id: "proper-m-0n0p0000p",
      matrix: Object.freeze([0, -1, 0, 1, 0, 0, 0, 0, 1] as const),
    }),
    Object.freeze({
      id: "proper-m-0p000nn00",
      matrix: Object.freeze([0, 1, 0, 0, 0, -1, -1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-0p000pp00",
      matrix: Object.freeze([0, 1, 0, 0, 0, 1, 1, 0, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-0p0n0000p",
      matrix: Object.freeze([0, 1, 0, -1, 0, 0, 0, 0, 1] as const),
    }),
    Object.freeze({
      id: "proper-m-0p0p0000n",
      matrix: Object.freeze([0, 1, 0, 1, 0, 0, 0, 0, -1] as const),
    }),
    Object.freeze({
      id: "proper-m-n0000n0n0",
      matrix: Object.freeze([-1, 0, 0, 0, 0, -1, 0, -1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-n0000p0p0",
      matrix: Object.freeze([-1, 0, 0, 0, 0, 1, 0, 1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-n000n000p",
      matrix: Object.freeze([-1, 0, 0, 0, -1, 0, 0, 0, 1] as const),
    }),
    Object.freeze({
      id: "proper-m-p0000n0p0",
      matrix: Object.freeze([1, 0, 0, 0, 0, -1, 0, 1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-p0000p0n0",
      matrix: Object.freeze([1, 0, 0, 0, 0, 1, 0, -1, 0] as const),
    }),
    Object.freeze({
      id: "proper-m-p000n000n",
      matrix: Object.freeze([1, 0, 0, 0, -1, 0, 0, 0, -1] as const),
    }),
  ]);
