/** Second half of the closed measured-part row fixture; order continues fixture A. */
export const ADMITTED_SOURCE_PART_ROWS_B = [
  // builtin.basic-parts/21. The moved-to official root supplies one top stud;
  // its checksum-pinned underside tube and the stud establish the exact Builder
  // frame that exclusively authors the two underside clutches.
  {
    id: "builtin:slope-1x2-45",
    ldrawId: "3040.dat",
    family: "slope",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 24,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -12, 10],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -12, -20], max: [10, 12, 20] },
    boundsLdu: { min: [-10, -16, -20], max: [10, 12, 20] },
    studs: 1,
    clutches: 2,
    bodyBoxes: 67,
    triangles: 178,
    vertices: 184,
    closureFiles: 11,
  },
  // builtin.basic-parts/22. The exact official shaft supplies render and
  // collision truth; one pinned LDCad A6x60 segment supplies three discrete
  // axle ports through the established 20 LDU station projection.
  {
    id: "builtin:axle-1x3",
    ldrawId: "4519.dat",
    family: "axle",
    widthStuds: 1,
    lengthStuds: 3,
    heightLdu: 12,
    orientationId: "upright-yaw-0",
    translationLdu: [0, 0, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-29.5, -6, -6], max: [29.5, 6, 6] },
    boundsLdu: { min: [-29.5, -6, -6], max: [29.5, 6, 6] },
    studs: 0,
    clutches: 0,
    axles: 3,
    bodyBoxes: 41,
    triangles: 176,
    vertices: 162,
    closureFiles: 4,
  },
  // builtin.basic-parts/23. The moved-to official closure supplies the open
  // Technic-brick shell; one pinned LDCad A6x1 segment supplies its transverse
  // female axle-hole endpoint without claiming collision clearance through it.
  {
    id: "builtin:technic-brick-1x2-axle-hole",
    ldrawId: "32064.dat",
    family: "technic-brick",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 24,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -12, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -12, -20], max: [10, 12, 20] },
    boundsLdu: { min: [-10, -16, -20], max: [10, 12, 20] },
    studs: 2,
    clutches: 2,
    axleHoles: 1,
    bodyBoxes: 23,
    triangles: 458,
    vertices: 576,
    closureFiles: 23,
  },
  // builtin.basic-parts/24. The regular square source and connector lattice are
  // quarter-turn symmetric, with yaw zero selected as the canonical declared
  // frame. Its exact LDCad shadow route authors all nine underside clutches; the
  // nominal stud profile applies only to validated stud/clutch edges, while
  // ordinary collision keeps the measured stud radius.
  {
    id: "builtin:plate-3x3",
    ldrawId: "11212.dat",
    family: "plate",
    widthStuds: 3,
    lengthStuds: 3,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-30, -4, -30], max: [30, 4, 30] },
    boundsLdu: { min: [-30, -8, -30], max: [30, 4, 30] },
    studs: 9,
    clutches: 9,
    bodyBoxes: 129,
    triangles: 844,
    vertices: 873,
    closureFiles: 10,
  },
  // builtin.basic-parts/25. The regular 2 x 2 plate shell keeps only the two
  // visible studs on one edge; the exact LDCad route independently authors
  // those two frames and all four regular underside clutches.
  {
    id: "builtin:plate-2x2-two-studs",
    ldrawId: "33909.dat",
    family: "plate",
    widthStuds: 2,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-20, -4, -20], max: [20, 4, 20] },
    boundsLdu: { min: [-20, -8, -20], max: [20, 4, 20] },
    studs: 2,
    clutches: 4,
    bodyBoxes: 41,
    triangles: 220,
    vertices: 242,
    closureFiles: 9,
  },
  // builtin.basic-parts/26. The width-first catalog frame rotates the regular
  // 1 x 5 source shell by one quarter turn. The exact LDCad route independently
  // authors its five visible stud frames and five underside clutch cells.
  {
    id: "builtin:plate-1x5",
    ldrawId: "78329.dat",
    family: "plate",
    widthStuds: 1,
    lengthStuds: 5,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -50], max: [10, 4, 50] },
    boundsLdu: { min: [-10, -8, -50], max: [10, 4, 50] },
    studs: 5,
    clutches: 5,
    bodyBoxes: 39,
    triangles: 460,
    vertices: 489,
    closureFiles: 9,
  },
  // builtin.basic-parts/27. These four bounded-prefix parts retain exact
  // official LDraw render/collision truth and exact LDCad connector routes.
  // The half-pitch 99563 center seat consumes both adjacent capacity cells;
  // it does not create a third independent full-pitch attachment cell.
  {
    id: "builtin:tile-1x2-chamfered-indented",
    ldrawId: "99563.dat",
    family: "tile",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -20], max: [10, 4, 20] },
    boundsLdu: { min: [-10, -4, -20], max: [10, 4, 20] },
    studs: 0,
    clutches: 3,
    bodyBoxes: 20,
    triangles: 228,
    vertices: 256,
    closureFiles: 10,
  },
  {
    id: "builtin:technic-brick-1x1-axle-hole",
    ldrawId: "73230.dat",
    family: "technic-brick",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 24,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -12, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -12, -10], max: [10, 12, 10] },
    boundsLdu: { min: [-10, -16, -10], max: [10, 12, 10] },
    studs: 1,
    clutches: 1,
    axleHoles: 1,
    bodyBoxes: 10,
    triangles: 294,
    vertices: 356,
    closureFiles: 18,
  },
  {
    id: "builtin:slope-1x1-double-45",
    ldrawId: "35464.dat",
    family: "slope",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 16,
    orientationId: "upright-yaw-0",
    translationLdu: [0, 8, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -8, -10], max: [10, 8, 10] },
    boundsLdu: { min: [-10, -8, -10], max: [10, 8, 10] },
    studs: 0,
    clutches: 1,
    bodyBoxes: 75,
    triangles: 52,
    vertices: 84,
    closureFiles: 5,
  },
  {
    id: "builtin:curved-slope-1x1-outside-bow",
    ldrawId: "49307.dat",
    family: "curved-slope",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 16,
    orientationId: "upright-yaw-0",
    translationLdu: [0, 8, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -8, -10], max: [10, 8, 10] },
    boundsLdu: { min: [-10, -8, -10], max: [10, 8, 10] },
    studs: 0,
    clutches: 1,
    bodyBoxes: 75,
    triangles: 100,
    vertices: 120,
    closureFiles: 7,
  },
  // builtin.basic-parts/28. Exact suffixed LDraw roots and LDCad declarations
  // define generic catalog geometry and connectors without reinterpreting the
  // quarantined Builder or booklet variant diagnostics.
  {
    id: "builtin:brick-1x2x2-without-understud",
    ldrawId: "3245c.dat",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 48,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -24, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -24, -20], max: [10, 24, 20] },
    boundsLdu: { min: [-10, -28, -20], max: [10, 24, 20] },
    studs: 2,
    clutches: 3,
    bodyBoxes: 25,
    triangles: 152,
    vertices: 206,
    closureFiles: 10,
  },
  {
    id: "builtin:brick-1x1x5-solid-stud",
    ldrawId: "2453b.dat",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 120,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -60, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -60, -10], max: [10, 60, 10] },
    boundsLdu: { min: [-10, -64, -10], max: [10, 60, 10] },
    studs: 1,
    clutches: 1,
    bodyBoxes: 5,
    triangles: 76,
    vertices: 97,
    closureFiles: 6,
  },
  // builtin.basic-parts/30. Exact official roots and exact LDCad routes admit
  // these two previously quarantined physical identities without aliasing the
  // distinct 28802 or 3245c constructions.
  {
    id: "builtin:bracket-1x2-1x4-rounded-corners",
    ldrawId: "10201.dat",
    family: "bracket",
    widthStuds: 4,
    lengthStuds: 1,
    heightLdu: 20,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -10, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-40, -10, -14], max: [40, 10, 10] },
    boundsLdu: { min: [-40, -14, -18], max: [40, 10, 10] },
    studs: 6,
    clutches: 2,
    bodyBoxes: 23,
    triangles: 660,
    vertices: 695,
    closureFiles: 21,
  },
  {
    id: "builtin:brick-1x2x2-inside-axle-holder",
    ldrawId: "3245b.dat",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 48,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -24, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -24, -20], max: [10, 24, 20] },
    boundsLdu: { min: [-10, -28, -20], max: [10, 24, 20] },
    studs: 2,
    clutches: 2,
    blindAxleHoles: 1,
    bodyBoxes: 29,
    triangles: 144,
    vertices: 190,
    closureFiles: 11,
  },
  // builtin.basic-parts/30. The existing jumper identity is promoted in place
  // from parametric geometry and two outer seats to its exact official surface,
  // measured collision field, and the LDCad-authored centered half-pitch seat.
  {
    id: "builtin:jumper-plate-1x2",
    ldrawId: "15573.dat",
    family: "jumper-plate",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -20], max: [10, 4, 20] },
    boundsLdu: { min: [-10, -8, -20], max: [10, 4, 20] },
    studs: 1,
    clutches: 3,
    bodyBoxes: 29,
    triangles: 220,
    vertices: 288,
    closureFiles: 11,
  },
] as const;
