/** First half of the closed measured-part row fixture; order is catalog evidence. */
export const ADMITTED_SOURCE_PART_ROWS_A = [
  {
    id: "builtin:tile-1x2-cut-right-45",
    ldrawId: "5092.dat",
    family: "tile",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -17], max: [10, 4, 20] },
    boundsLdu: { min: [-10, -4, -17], max: [10, 4, 20] },
    studs: 0,
    clutches: 1,
    bodyBoxes: 44,
    triangles: 84,
    vertices: 132,
    closureFiles: 7,
  },
  {
    id: "builtin:plate-1x2-round-end",
    ldrawId: "35480.dat",
    family: "plate",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -20], max: [10, 4, 20] },
    boundsLdu: { min: [-10, -8, -20], max: [10, 4, 20] },
    studs: 2,
    clutches: 2,
    bodyBoxes: 72,
    triangles: 604,
    vertices: 525,
    closureFiles: 16,
  },
  {
    id: "builtin:wedge-plate-2x4-wing",
    ldrawId: "51739.dat",
    family: "wedge-plate",
    widthStuds: 2,
    lengthStuds: 4,
    heightLdu: 8,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-20, -4, -38.5], max: [20, 4, 38.5] },
    boundsLdu: { min: [-20, -8, -38.5], max: [20, 4, 38.5] },
    studs: 4,
    clutches: 4,
    bodyBoxes: 115,
    triangles: 424,
    vertices: 482,
    closureFiles: 20,
  },
  {
    id: "builtin:corner-plate-3x3",
    ldrawId: "77844.dat",
    family: "corner-plate",
    widthStuds: 3,
    lengthStuds: 3,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [20, 20],
    bodyBoundsLdu: { min: [-10, -4, -10], max: [50, 4, 50] },
    boundsLdu: { min: [-10, -8, -10], max: [50, 4, 50] },
    studs: 5,
    clutches: 5,
    bodyBoxes: 50,
    triangles: 485,
    vertices: 530,
    closureFiles: 11,
  },
  {
    id: "builtin:curved-slope-1x4-double",
    ldrawId: "93273.dat",
    family: "curved-slope",
    widthStuds: 1,
    lengthStuds: 4,
    heightLdu: 16,
    orientationId: "upright-yaw-0",
    translationLdu: [0, 8, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -8.00016098, -40], max: [10, 8, 40] },
    boundsLdu: { min: [-10, -8.00016098, -40], max: [10, 8, 40] },
    studs: 0,
    clutches: 4,
    bodyBoxes: 275,
    triangles: 328,
    vertices: 427,
    closureFiles: 21,
  },
  // builtin.basic-parts/8. LEGO Builder's 107-record pack has no record of any
  // of these three, so LDraw alone leaves each with studs and zero clutch cells
  // — a part that can be built on and never placed on anything. Their clutch
  // cells are the LDCad shadow library's, composed through the part's own LDraw
  // reference tree and driven through the same clutch-room probe.
  {
    id: "builtin:plate-3x3-corner-round",
    ldrawId: "30357.dat",
    family: "plate",
    widthStuds: 3,
    lengthStuds: 3,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [20, 20],
    bodyBoundsLdu: { min: [-10, -4, -10], max: [50, 4, 50] },
    boundsLdu: { min: [-10, -8, -10], max: [50, 4, 50] },
    studs: 8,
    clutches: 8,
    bodyBoxes: 157,
    triangles: 904,
    vertices: 946,
    closureFiles: 27,
  },
  {
    id: "builtin:wedge-plate-3x3-cut-corner",
    ldrawId: "2450.dat",
    family: "wedge-plate",
    widthStuds: 3,
    lengthStuds: 3,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-30, -4, -30], max: [30, 4, 30] },
    boundsLdu: { min: [-30, -8, -30], max: [30, 4, 30] },
    studs: 6,
    clutches: 6,
    bodyBoxes: 168,
    triangles: 650,
    vertices: 712,
    closureFiles: 15,
  },
  {
    id: "builtin:corner-plate-2x2-round",
    ldrawId: "79491.dat",
    family: "corner-plate",
    widthStuds: 2,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [10, 10],
    bodyBoundsLdu: { min: [-10, -4, -10], max: [30, 4, 30] },
    boundsLdu: { min: [-10, -8, -10], max: [30, 4, 30] },
    studs: 2,
    clutches: 2,
    bodyBoxes: 53,
    triangles: 302,
    vertices: 354,
    closureFiles: 24,
  },
  // builtin.basic-parts/14. LDraw owns surface/frame/collision; LDCad owns clutch.
  {
    id: "builtin:tile-1x1-quarter-round",
    ldrawId: "25269.dat",
    family: "tile",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -4, -10], max: [10, 4, 10] },
    boundsLdu: { min: [-10, -4, -10], max: [10, 4, 10] },
    studs: 0,
    clutches: 1,
    bodyBoxes: 26,
    triangles: 96,
    vertices: 146,
    closureFiles: 13,
  },
  // builtin.basic-parts/15. The horizontal stud frames are source truth even
  // though the unchanged upright transform policy cannot yet mate to them.
  {
    id: "builtin:bracket-1x2-1x4-rounded-bottom",
    ldrawId: "28802.dat",
    family: "bracket",
    widthStuds: 4,
    lengthStuds: 1,
    heightLdu: 20,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -10, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-40, -10, -14], max: [40, 10, 10] },
    boundsLdu: { min: [-40, -14, -18], max: [40, 10, 10] },
    studs: 6,
    clutches: 2,
    bodyBoxes: 23,
    triangles: 618,
    vertices: 663,
    closureFiles: 19,
  },
  // builtin.basic-parts/16. The official and shadow subparts share the exact
  // upright frame; the unframed Builder native field is retained but unused.
  {
    id: "builtin:tile-2x2-triangular",
    ldrawId: "35787.dat",
    family: "tile",
    widthStuds: 2,
    lengthStuds: 2,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-20, -4, -20], max: [17, 4, 17] },
    boundsLdu: { min: [-20, -4, -20], max: [17, 4, 17] },
    studs: 0,
    clutches: 3,
    bodyBoxes: 66,
    triangles: 128,
    vertices: 161,
    closureFiles: 22,
  },
  // builtin.basic-parts/17. The roller is above the local stud-bearing shoe
  // deck, so the measured envelope is deliberately not plate-shaped.
  {
    id: "builtin:roller-skate",
    ldrawId: "11253.dat",
    family: "minifig-accessory",
    widthStuds: 1,
    lengthStuds: 1,
    heightLdu: 8,
    orientationId: "upright-yaw-0",
    translationLdu: [0, -4, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -7, -14], max: [10, 4, 14] },
    boundsLdu: { min: [-10, -8, -14], max: [10, 4, 14] },
    studs: 1,
    clutches: 1,
    bodyBoxes: 78,
    triangles: 690,
    vertices: 705,
    closureFiles: 17,
  },
  // builtin.basic-parts/18. The source-derived arch surface supplies six studs;
  // the exact pinned Builder frame supplies only its two end clutch cells.
  {
    id: "builtin:arch-1x6-thin-top",
    ldrawId: "15254.dat",
    family: "arch",
    widthStuds: 1,
    lengthStuds: 6,
    heightLdu: 48,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -24, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -24, -60], max: [10, 24, 60] },
    boundsLdu: { min: [-10, -28, -60], max: [10, 24, 60] },
    studs: 6,
    clutches: 2,
    bodyBoxes: 167,
    triangles: 548,
    vertices: 594,
    closureFiles: 15,
  },
  // builtin.basic-parts/19. The source and shadow closure agree on two
  // side-facing studs; the same shadow root authors four underside clutches.
  {
    id: "builtin:bracket-2x2-1x2-vertical-studs",
    ldrawId: "41682.dat",
    family: "bracket",
    widthStuds: 2,
    lengthStuds: 2,
    heightLdu: 28,
    orientationId: "upright-yaw-0",
    translationLdu: [0, 6, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-20, -14, -20], max: [20, 14, 20] },
    boundsLdu: { min: [-20, -14, -20], max: [20, 14, 20] },
    studs: 2,
    clutches: 4,
    bodyBoxes: 54,
    triangles: 336,
    vertices: 399,
    closureFiles: 14,
  },
  // builtin.basic-parts/20. The source supplies two top studs; the exact pinned
  // Builder frame exclusively authors the two underside clutches.
  {
    id: "builtin:brick-1x2-grille",
    ldrawId: "2877.dat",
    family: "brick",
    widthStuds: 1,
    lengthStuds: 2,
    heightLdu: 24,
    orientationId: "upright-yaw-90",
    translationLdu: [0, -12, 0],
    connectorGridCenterLdu: [0, 0],
    bodyBoundsLdu: { min: [-10, -12, -20], max: [10, 12, 20] },
    boundsLdu: { min: [-10, -16, -20], max: [10, 12, 20] },
    studs: 2,
    clutches: 2,
    bodyBoxes: 26,
    triangles: 264,
    vertices: 375,
    closureFiles: 7,
  },
] as const;
