// Generated by `npm run pin:generate`. Do not edit by hand.
//
// The digest of the one deterministic maker run this repository pins, and the
// catalog truth it was taken against. See packages/generation/src/run-pin.ts
// for why both are recorded.
import type { RunPin } from "./run-pin.ts";

export const DETERMINISTIC_RUN_PIN: RunPin = {
  catalogVersion: "builtin.basic-parts/7",
  catalogTruthHash: "sha256:f26a1ba141ca0485f1bf046c68d94082497fcd8dcea85906723a389a09ec55d2",
  populationDigest: "sha256:87f224fc3e8c2c2766292a23e4ba1fe44996d76610231e98b3eabda13e117b50",
};
