// Generated by `npm run pin:generate`. Do not edit by hand.
//
// The digest of the one deterministic maker run this repository pins, and the
// catalog truth it was taken against. See packages/generation/src/run-pin.ts
// for why both are recorded.
import type { RunPin } from "./run-pin.ts";

export const DETERMINISTIC_RUN_PIN: RunPin = {
  catalogVersion: "builtin.basic-parts/4",
  catalogTruthHash: "sha256:4606e0a2b716aa971b8ec57d1584238c39b89ffa8a84b898d516d3f71c9f133d",
  populationDigest: "sha256:644f106b617e1b69a5751b9b8cfce576cfed21345a9532538e1b22d60cccac3e",
};
