// Generated by `npm run pin:generate`. Do not edit by hand.
//
// The digest of the one deterministic maker run this repository pins, and the
// catalog truth it was taken against. See packages/generation/src/run-pin.ts
// for why both are recorded.
import type { RunPin } from "./run-pin.ts";

export const DETERMINISTIC_RUN_PIN: RunPin = {
  catalogVersion: "builtin.basic-parts/6",
  catalogTruthHash: "sha256:590a94c9b9498faace4b29b74c4c9ba8352d644365585d9aeb96b4a7c53bdb7f",
  populationDigest: "sha256:4be24daa6ce92d977553c605a62ef14f56de37182e26a92820e12d478391986b",
};
