export const STEP44_SOURCE_EXTENSIONS = [".ts", ".tsx", ".mts", ".mjs", ".js", ".ps1"] as const;
export const STEP44_FS_MODULES = new Set(["fs", "fs/promises", "node:fs", "node:fs/promises"]);
export const STEP44_CHILD_PROCESS_MODULES = new Set(["child_process", "node:child_process"]);
export const STEP44_MODULE_MODULES = new Set(["module", "node:module"]);
export const STEP44_PROCESS_MODULES = new Set(["process", "node:process"]);
export const STEP44_FORBIDDEN_EXECUTION_MODULES = new Set([
  "cluster",
  "inspector",
  "node:cluster",
  "node:inspector",
  "node:vm",
  "node:worker_threads",
  "vm",
  "worker_threads",
]);
export const STEP44_FORBIDDEN_PROCESS_LOADERS = new Set([
  "_linkedBinding",
  "binding",
  "dlopen",
  "getBuiltinModule",
  "mainModule",
]);
export const STEP44_FORBIDDEN_GLOBAL_EXECUTORS = new Set([
  "Function",
  "SharedWorker",
  "WebAssembly",
  "Worker",
  "eval",
  "importScripts",
  "require",
]);
export const STEP44_CHILD_PROCESS_PRIMITIVES = new Set([
  "exec",
  "execFile",
  "execFileSync",
  "execSync",
  "fork",
  "spawn",
  "spawnSync",
]);
export const STEP44_FILESYSTEM_READ_PRIMITIVES = new Set([
  "access",
  "accessSync",
  "createReadStream",
  "existsSync",
  "fstat",
  "fstatSync",
  "lstat",
  "lstatSync",
  "open",
  "openSync",
  "opendir",
  "opendirSync",
  "read",
  "readSync",
  "readFile",
  "readFileSync",
  "readdir",
  "readdirSync",
  "readlink",
  "readlinkSync",
  "realpath",
  "realpathSync",
  "stat",
  "statSync",
]);
export const STEP44_FILESYSTEM_WRITE_PRIMITIVES = new Set([
  "appendFile",
  "appendFileSync",
  "chmod",
  "chmodSync",
  "close",
  "closeSync",
  "copyFile",
  "copyFileSync",
  "createWriteStream",
  "fchmod",
  "fchmodSync",
  "fsync",
  "fsyncSync",
  "ftruncate",
  "ftruncateSync",
  "link",
  "linkSync",
  "mkdir",
  "mkdirSync",
  "mkdtemp",
  "mkdtempSync",
  "rename",
  "renameSync",
  "rm",
  "rmSync",
  "rmdir",
  "rmdirSync",
  "symlink",
  "symlinkSync",
  "truncate",
  "truncateSync",
  "unlink",
  "unlinkSync",
  "write",
  "writeSync",
  "writeFile",
  "writeFileSync",
]);
export const STEP44_FILESYSTEM_METADATA_PRIMITIVES = new Set(["constants", "Dirent", "Stats"]);
export const STEP44_BOUNDED_READER_PRIMITIVES = new Set([
  "readContainedBoundedRegularFile",
  "readRealBuildPrefix50Step44ReviewArtifact",
  "resolveRealBuildPrefix50Step44ReviewArtifact",
]);
