import { describe, expect, it } from "vitest";

import {
  describeStaleNotices,
  describeStaleProtocolArtifact,
  describeStaleRunPin,
  describeTextDifference,
  exportedNames,
  nameSome,
  noticeRows,
} from "./generated-file-staleness.mjs";

const CATALOG_HASH = `sha256:${"a".repeat(64)}`;
const DIGEST = `sha256:${"3".repeat(64)}`;
const OTHER_DIGEST = `sha256:${"4".repeat(64)}`;

const runPinFile = ({
  banner = "// The digest of the one deterministic maker run this repository pins.",
  catalogVersion = "builtin.basic-parts/8",
  catalogTruthHash = CATALOG_HASH,
  populationDigest = DIGEST,
} = {}) =>
  [
    "// Generated by `npm run pin:generate`. Do not edit by hand.",
    banner,
    'import type { RunPin } from "./run-pin.ts";',
    "",
    "export const DETERMINISTIC_RUN_PIN: RunPin = {",
    `  catalogVersion: "${catalogVersion}",`,
    `  catalogTruthHash: "${catalogTruthHash}",`,
    `  populationDigest: "${populationDigest}",`,
    "};",
    "",
  ].join("\n");

const liveRunPin = {
  catalogVersion: "builtin.basic-parts/8",
  catalogTruthHash: CATALOG_HASH,
  populationDigest: DIGEST,
};

const noticesFile = (rows) =>
  [
    "# Third-party notices",
    "",
    "| Package | Version | Declared license | Registry source |",
    "| --- | --- | --- | --- |",
    ...rows.map(
      ([name, version, license, source]) => `| ${name} | ${version} | ${license} | ${source} |`,
    ),
    "",
  ].join("\n");

const LOCKFILE_ROWS = [
  ["ajv", "8.20.0", "MIT", "https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz"],
  ["acorn", "8.17.0", "MIT", "https://registry.npmjs.org/acorn/-/acorn-8.17.0.tgz"],
];

describe("describeTextDifference", () => {
  it("reports nothing when the bytes match, so it can double as the staleness test", () => {
    expect(describeTextDifference("same\n", "same\n")).toBeNull();
  });

  it("names line endings as the whole difference rather than pointing at a line", () => {
    const description = describeTextDifference("one\r\ntwo\r\n", "one\ntwo\n");
    expect(description).toBe(
      "only the line endings differ — on disk CRLF endings, generated LF endings",
    );
  });

  it("names the first differing line, both sides of it, and the line counts", () => {
    const description = describeTextDifference("one\ntwo\n", "one\nTWO\nthree\n");
    expect(description).toContain("line 2 is the first that differs");
    expect(description).toContain("3 lines on disk against 4 lines generated");
    expect(description).toContain('on disk "two", generated "TWO"');
  });

  it("quotes the line so an invisible difference is visible", () => {
    expect(describeTextDifference("a\t\n", "a \n")).toContain('on disk "a\\t", generated "a "');
    expect(describeTextDifference("a \n", "a\n")).toContain("differ only in trailing whitespace");
  });

  it("reports the extra line on whichever side has it, rather than quoting undefined", () => {
    expect(describeTextDifference("one\n", "one\ntwo\n")).toContain('on disk "", generated "two"');
    expect(describeTextDifference("one\ntwo\nthree", "one\ntwo")).toContain(
      'on disk "three", generated no such line',
    );
  });
});

describe("nameSome", () => {
  it("reads as prose at every length and counts what it does not name", () => {
    expect(nameSome([])).toBe("");
    expect(nameSome(["a"])).toBe("a");
    expect(nameSome(["a", "b"])).toBe("a and b");
    expect(nameSome(["a", "b", "c"])).toBe("a, b and c");
    expect(nameSome(["a", "b", "c"], 2)).toBe("a, b and 1 more");
  });
});

describe("describeStaleRunPin", () => {
  // The defect this file exists to prevent: the check compares whole file bytes
  // and used to report every difference as a moved digest, which printed the
  // same digest twice on a checkout that only changed line endings.
  it("never prints one pinned value as both held and produced", () => {
    for (const previous of [
      runPinFile().replaceAll("\n", "\r\n"),
      runPinFile({ banner: "// A reworded header." }),
    ]) {
      const message = describeStaleRunPin(previous, runPinFile(), liveRunPin);
      expect(message).toContain("stale in its file bytes only");
      expect(message).toContain("Every pinned value already matches this build");
      expect(message.match(new RegExp(DIGEST, "g"))).toHaveLength(1);
    }
  });

  it("names line endings as the cause when that is the cause", () => {
    expect(
      describeStaleRunPin(runPinFile().replaceAll("\n", "\r\n"), runPinFile(), liveRunPin),
    ).toContain("only the line endings differ");
  });

  it("names only the field that moved, and says the others did not", () => {
    const message = describeStaleRunPin(
      runPinFile({ populationDigest: OTHER_DIGEST }),
      runPinFile(),
      liveRunPin,
    );
    expect(message).toContain("populationDigest disagrees with this build");
    expect(message).toContain(
      `populationDigest: file holds ${OTHER_DIGEST}, this build produces ${DIGEST}`,
    );
    expect(message).toContain("catalogVersion: unchanged at builtin.basic-parts/8");
    expect(message).toContain(`catalogTruthHash: unchanged at ${CATALOG_HASH}`);
    // Catalog truth held still, so this is the case that must not be re-pinned blind.
    expect(message).toContain("the change is in the deterministic path itself");
    expect(message).not.toContain("stale in its file bytes only");
  });

  it("distinguishes routine catalog churn from a moved deterministic path", () => {
    const message = describeStaleRunPin(
      runPinFile({
        catalogVersion: "builtin.basic-parts/7",
        catalogTruthHash: `sha256:${"b".repeat(64)}`,
        populationDigest: OTHER_DIGEST,
      }),
      runPinFile(),
      liveRunPin,
    );
    expect(message).toContain("catalogVersion, catalogTruthHash and populationDigest disagree");
    expect(message).toContain("a catalog change moves this digest as a matter of course");
    expect(message).not.toContain("the change is in the deterministic path itself");
  });

  it("separates a file that is absent from a file whose values cannot be read", () => {
    expect(describeStaleRunPin(null, runPinFile(), liveRunPin)).toContain("has never been written");
    const message = describeStaleRunPin("export const nothing = 1;\n", runPinFile(), liveRunPin);
    expect(message).toContain("file holds no readable catalogVersion");
    expect(message).toContain("file holds no readable populationDigest");
  });
});

describe("describeStaleNotices", () => {
  it("says no dependency moved when none did, and counts the rows it checked", () => {
    const expected = noticesFile(LOCKFILE_ROWS);
    const message = describeStaleNotices(expected.replaceAll("\n", "\r\n"), expected);
    expect(message).toContain("stale in its file bytes only");
    expect(message).toContain("All 2 dependency rows already match package-lock.json");
    expect(message).toContain("only the line endings differ");
  });

  it("names what was added, removed and relicensed, with the licenses on both sides", () => {
    const held = noticesFile([
      ["ajv", "8.20.0", "GPL-3.0", "https://registry.npmjs.org/ajv/-/ajv-8.20.0.tgz"],
      ["dropped", "1.0.0", "MIT", "https://registry.npmjs.org/dropped/-/dropped-1.0.0.tgz"],
    ]);
    const message = describeStaleNotices(held, noticesFile(LOCKFILE_ROWS));
    expect(message).toContain("1 added (acorn@8.17.0)");
    expect(message).toContain("1 removed (dropped@1.0.0)");
    expect(message).toContain("1 with a changed license or registry source (ajv@8.20.0)");
    expect(message).toContain("file holds GPL-3.0 from");
    expect(message).toContain("the lockfile has MIT from");
  });

  it("says the file is absent rather than calling it stale", () => {
    expect(describeStaleNotices(null, noticesFile(LOCKFILE_ROWS))).toContain(
      "THIRD_PARTY_NOTICES.md does not exist",
    );
  });

  it("keeps an escaped pipe inside a cell rather than splitting on it", () => {
    const rows = noticeRows(
      noticesFile([["dual", "1.0.0", "MIT \\| Apache-2.0", "https://example.invalid/dual.tgz"]]),
    );
    expect(rows.get("dual@1.0.0")).toBe("MIT \\| Apache-2.0 from https://example.invalid/dual.tgz");
  });
});

describe("describeStaleProtocolArtifact", () => {
  const generated = [
    "// Generated from schemas/protocol.schema.json. Do not edit by hand.",
    "export type Hash = string;",
    "export const validateRunEventV1: ValidateFunction<unknown>;",
    "",
  ].join("\n");

  it("says the exports held still when the difference is inside a declaration", () => {
    const message = describeStaleProtocolArtifact(
      "types.generated.ts",
      generated.replace("export type Hash = string;", "export type Hash = `sha256:${string}`;"),
      generated,
    );
    expect(message).toContain("line 2 is the first that differs");
    expect(message).toContain("Its 2 exported names are unchanged");
  });

  it("names the exported symbols that moved", () => {
    const message = describeStaleProtocolArtifact(
      "validators.generated.d.ts",
      generated.replace("export const validateRunEventV1: ValidateFunction<unknown>;\n", ""),
      generated,
    );
    expect(message).toContain("Exported names moved: 1 added (validateRunEventV1)");
    expect(exportedNames(generated)).toEqual(["Hash", "validateRunEventV1"]);
  });

  it("separates an artifact never written from a stale one", () => {
    expect(describeStaleProtocolArtifact("types.generated.ts", undefined, generated)).toContain(
      "has never been written",
    );
  });

  it("names line endings rather than a schema change on a translated checkout", () => {
    const message = describeStaleProtocolArtifact(
      "validators.generated.js",
      generated.replaceAll("\n", "\r\n"),
      generated,
    );
    expect(message).toContain("only the line endings differ");
    expect(message).toContain("exported names are unchanged");
  });
});
