"""Stable generated-file headers shared by measured-part emitters."""

GENERATED_HEADER = """\
// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// {archive_sha256}), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \\
//     --official <ldraw-complete-2026-07.zip> \\
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \\
//     --shadow <ldcad-shadow-20260802> \\
//     --pilot <set-6651557-source-pilot.json> \\
//     --builder-frame <set-6651557-builder-ldraw-frame.json>
"""

RENDER_ONLY_GENERATED_HEADER = """\
// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// {archive_sha256}). These render-only declarations consume only that pinned
// official archive and no other evidence source. Do not hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \\
//     --official <ldraw-complete-2026-07.zip> \\
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \\
//     --shadow <ldcad-shadow-20260802> \\
//     --pilot <set-6651557-source-pilot.json> \\
//     --builder-frame <set-6651557-builder-ldraw-frame.json>
"""
