"""Render the catalog's three generated measured-part tables as TypeScript.

Every table here comes from the same `MeasuredPart`, so its generated fields
stay aligned. Eight measured definitions consume all fields; the four `/12`
render promotions consume mesh and visual bounds while the catalog factory
retains their preceding connector, allowance and collision arrays. The emitter
canonicalizes this output with the workspace-pinned Prettier before comparison.

This renders text. It admits nothing and reads nothing from the catalog.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Sequence

from ldcad_shadow_connectors import SHADOW_COMPOSITION_ID
from ldraw_source_archive import SourceRecord
from measured_part_tables import (
    BUILDER_CONNECTIVITY_CONNECTOR_SOURCE,
    BUILDER_CONNECTOR_SOURCE,
    LDCAD_SHADOW_CONNECTOR_SOURCE,
    MeasuredPart,
)

GENERATED_HEADER = """\
// Generated by scripts/emit-measured-part-tables.py from the byte-pinned official
// LDraw archive (sha256
// {archive_sha256}), the pinned
// Builder-to-LDraw frame report and the pinned LDCad shadow library. Do not
// hand-edit. Reproduce with:
//
//   python -B scripts/emit-measured-part-tables.py \\
//     --official <ldraw-complete-2026-07.zip> \\
//     --unofficial <ldraw-unofficial-2026-08-02.zip> \\
//     --shadow <ldcad-shadow-20260802> \\
//     --pilot <set-6651557-source-pilot.json> \\
//     --builder-frame <set-6651557-builder-ldraw-frame.json>
"""


def canonical_typescript(repository: Path, target: Path, source: str) -> str:
    """Format generated TypeScript with the workspace-pinned Prettier."""

    prettier = repository / "node_modules/prettier/bin/prettier.cjs"
    if not prettier.is_file():
        raise SystemExit(
            f"Measured-part table generation needs the pinned Prettier at {prettier}. "
            "Run npm ci in the repository before generating or checking tables."
        )
    result = subprocess.run(
        ["node", str(prettier), "--stdin-filepath", str(target)],
        input=source,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        reason = result.stderr.strip() or f"exit {result.returncode}"
        raise SystemExit(f"Prettier could not canonicalize generated table {target}: {reason}.")
    return result.stdout


def enforce_generated_check(drifted: Sequence[str]) -> None:
    """Make check mode a real refusal rather than a report-only comparison."""

    if not drifted:
        return
    raise SystemExit(
        "Measured-part generated tables do not reproduce their canonical committed bytes: "
        f"{', '.join(drifted)}. Run this command without --check against the same pinned "
        "inputs, review the resulting diff, and commit the regenerated tables."
    )


def number_literal(value: float) -> str:
    """One measured LDU coordinate as the shortest TypeScript number that is it.

    An integral measurement prints without a fractional part, matching what a
    TypeScript number literal round-trips to, so the table reads as the integer
    lattice it mostly is.
    """

    if value != value or value in (float("inf"), float("-inf")):
        raise ValueError(f"Cannot emit non-finite measured coordinate {value!r}.")
    if float(value).is_integer() and abs(value) < 2**53:
        return str(int(value))
    return repr(float(value))


def _numbers(values: Sequence[float]) -> str:
    return ", ".join(number_literal(value) for value in values)


def _string(value: str) -> str:
    if "\\" in value or '"' in value or "\n" in value or "\r" in value:
        raise ValueError(
            f"Measured source text {value!r} contains a character this emitter does not "
            "escape; widen the escaping deliberately rather than emitting broken TypeScript."
        )
    return f'"{value}"'


def _exact_bounds_lines(
    field: str, bounds: tuple[tuple[str, str, str], tuple[str, str, str]]
) -> list[str]:
    """An exact bound stays one axis per line, however short its numbers are.

    A newline after the brace is what stops prettier collapsing the pair onto one
    line, so the six measured decimals of a part stay readable side by side.
    """

    minimum = ", ".join(_string(value) for value in bounds[0])
    maximum = ", ".join(_string(value) for value in bounds[1])
    return [f"    {field}: {{", f"      min: [{minimum}],", f"      max: [{maximum}],", "    },"]


def render_mesh_assets(parts: Sequence[MeasuredPart], archive_sha256: str) -> str:
    """`mesh-assets-6651557.ts`: the bundled render meshes, frame-local."""

    lines = [GENERATED_HEADER.format(archive_sha256=archive_sha256), ""]
    lines.append('import type { PreloadedMeshAsset } from "./mesh-assets.ts";')
    lines.append("")
    for part in parts:
        design = part.plan.design_id
        lines.append(f"const POSITIONS_{design} = [{_numbers(part.positions_ldu)}] as const;")
        lines.append("")
        lines.append(f"const INDICES_{design} = [{_numbers(part.indices)}] as const;")
    lines.append("/**")
    lines.append(
        f" * The {len(parts)} bundled set 6651557 render meshes, in their immutable asset-local"
    )
    lines.append(" * LDraw frame. Each part's `assetToCatalogFrame` normalizes them exactly once.")
    lines.append(" */")
    lines.append(
        "export const SET_6651557_MESH_ASSETS: Readonly<Record<string, PreloadedMeshAsset>> = "
        "Object.freeze({"
    )
    for part in parts:
        design = part.plan.design_id
        groups = [f'{{ role: "body", triangleStart: 0, triangleCount: {part.body_triangle_count} }}']
        if part.stud_triangle_count:
            groups.append(
                f'{{ role: "stud", triangleStart: {part.body_triangle_count}, '
                f"triangleCount: {part.stud_triangle_count} }}"
            )
        lines.append(f"  {_string(part.mesh_asset_id)}: {{")
        lines.append(f"    assetId: {_string(part.mesh_asset_id)},")
        lines.append(f"    positionsLdu: POSITIONS_{design},")
        lines.append(f"    indices: INDICES_{design},")
        lines.append(f"    groups: [{', '.join(groups)}],")
        lines.append("  },")
    lines.append("});")
    return "\n".join(lines) + "\n"


def _connector_source_block(part: MeasuredPart, shadow_identity: dict[str, object]) -> list[str]:
    if part.plan.connector_source != LDCAD_SHADOW_CONNECTOR_SOURCE:
        return []
    files = ", ".join(_string(path) for path in part.shadow_files)
    return [
        "    ldcadShadowSource: {",
        f"      libraryId: {_string(str(shadow_identity['libraryId']))},",
        f"      commit: {_string(str(shadow_identity['commit']))},",
        f"      manifestSha256: {_string(str(shadow_identity['manifestSha256']))},",
        f"      compositionId: {_string(SHADOW_COMPOSITION_ID)},",
        f"      shadowFiles: [{files}],",
        "    },",
    ]


def _builder_source_block(part: MeasuredPart, builder: dict[str, dict[str, str]]) -> list[str]:
    if part.plan.connector_source != BUILDER_CONNECTOR_SOURCE:
        return []
    record = builder[part.plan.design_id]
    return [
        "    builderSource: {",
        f"      revision: {_string(record['revision'])},",
        f"      recordSha256: {_string(record['recordSha256'])},",
        f"      frameSha256: {_string(record['frameSha256'])},",
        "    },",
    ]


def _builder_connectivity_source_block(part: MeasuredPart) -> list[str]:
    if part.plan.connector_source != BUILDER_CONNECTIVITY_CONNECTOR_SOURCE:
        return []
    fact = part.plan.builder_connectivity_fact
    assert fact is not None
    lines = [
        "    builderConnectivitySource: {",
        '      backingMode: "source-verified-partial-overhang",',
        f"      sourceId: {_string(fact.source_id)},",
        f"      sourceRevision: {_string(fact.source_revision)},",
        f"      manifestSha256: {_string(fact.manifest_sha256)},",
        f"      manifestMd5: {_string(fact.manifest_md5)},",
        f"      bundleSha256: {_string(fact.bundle_sha256)},",
        f"      primitiveXmlSha256: {_string(fact.primitive_xml_sha256)},",
        f"      independentSourceId: {_string(fact.independent_source_id)},",
        f"      independentSourceRevision: {_string(fact.independent_source_revision)},",
        f"      independentPartSha256: {_string(fact.independent_part_sha256)},",
        f"      independentSubpartSha256: {_string(fact.independent_subpart_sha256)},",
        f"      extractorId: {_string(fact.extractor_id)},",
        f"      normalizedClutchOffsetsSha256: {_string(fact.normalized_clutch_offsets_sha256)},",
        "      overrides: [",
    ]
    for x, z, overhang in fact.partial_overhangs:
        lines.extend(
            [
                "        {",
                f"          positionLdu: [{number_literal(x)}, {number_literal(z)}],",
                '          kind: "source-verified-partial-overhang",',
                f"          maximumOuterOverhangLdu: {number_literal(overhang)},",
                "        },",
            ]
        )
    lines.extend(["      ],", "    },"])
    return lines


def render_blueprints(
    parts: Sequence[MeasuredPart],
    archive_sha256: str,
    builder: dict[str, dict[str, str]],
    shadow_identity: dict[str, object],
) -> str:
    """`part-blueprints-6651557-measured.ts`: layers 2, 3 and 4 of every part."""

    lines = [GENERATED_HEADER.format(archive_sha256=archive_sha256), ""]
    lines.append('import type { MeasuredPartBlueprint } from "./measured-part-types.ts";')
    lines.append("")
    lines.append("export const SET_6651557_MEASURED_BLUEPRINTS = [")
    for part in parts:
        plan = part.plan
        lines.append("  {")
        lines.append(f"    designId: {_string(plan.design_id)},")
        lines.append(f"    ldrawId: {_string(f'{plan.design_id}.dat')},")
        lines.append(f"    family: {_string(plan.family)},")
        lines.append(f"    widthStuds: {plan.width_studs},")
        lines.append(f"    lengthStuds: {plan.length_studs},")
        if plan.variant is not None:
            lines.append(f"    variant: {_string(plan.variant)},")
        lines.append(f"    heightLdu: {plan.height_ldu},")
        lines.append(f"    meshAssetId: {_string(part.mesh_asset_id)},")
        lines.append("    assetToCatalogFrame: {")
        lines.append('      schemaVersion: "mesh-asset-to-catalog-frame/1",')
        lines.append(f"      orientationId: {_string(plan.orientation_id)},")
        lines.append(f"      translationLdu: [{_numbers(plan.translation_ldu)}],")
        lines.append("    },")
        lines.append(
            f"    connectorGridCenterLdu: [{_numbers(plan.connector_grid_center_ldu)}],"
        )
        lines.extend(_exact_bounds_lines("exactBodyBoundsLdu", part.exact_body_bounds))
        lines.extend(_exact_bounds_lines("exactBoundsLdu", part.exact_bounds))
        studs = ", ".join(f"[{_numbers(row)}]" for row in part.studs_ldu)
        lines.append(f"    studsLdu: [{studs}],")
        clutches = ", ".join(f"[{_numbers(row)}]" for row in part.clutches_ldu)
        lines.append(f"    clutchesLdu: [{clutches}],")
        lines.append(f"    bodyBoxesLdu: [{_numbers(part.body_boxes_ldu)}],")
        lines.append("    ldrawSource: {")
        lines.append(f"      title: {_string(part.root.title)},")
        lines.append(f"      author: {_string(part.root.author)},")
        lines.append(f"      ldrawOrg: {_string(part.root.ldraw_org)},")
        lines.append(f"      licenseExpression: {_string(part.root.license_expression)},")
        lines.append(f"      rootSha256: {_string(part.root.sha256)},")
        lines.append(f"      closureFileCount: {len(part.closure)},")
        lines.append("    },")
        lines.extend(_builder_source_block(part, builder))
        lines.extend(_builder_connectivity_source_block(part))
        lines.extend(_connector_source_block(part, shadow_identity))
        lines.append("  },")
    lines.append("] as const satisfies readonly MeasuredPartBlueprint[];")
    return "\n".join(lines) + "\n"


def bundled_file_table(
    parts: Sequence[MeasuredPart],
) -> tuple[list[SourceRecord], dict[str, list[int]]]:
    """Every file in every bundled closure, deduplicated and path-ordered."""

    records: dict[str, SourceRecord] = {}
    for part in parts:
        for record in part.closure:
            existing = records.get(record.path)
            if existing is not None and existing.sha256 != record.sha256:
                raise ValueError(
                    f"LDraw file {record.path} resolves to {record.sha256} for "
                    f"{part.plan.design_id} and {existing.sha256} elsewhere; one bundled path "
                    "cannot carry two different files."
                )
            records[record.path] = record
    ordered = [records[path] for path in sorted(records)]
    index_by_path = {record.path: index for index, record in enumerate(ordered)}
    closures = {
        part.plan.design_id: sorted(index_by_path[record.path] for record in part.closure)
        for part in parts
    }
    return ordered, closures


def render_bundled_sources(
    parts: Sequence[MeasuredPart], archive: dict[str, object]
) -> str:
    """`ldraw-bundled-sources-6651557.ts`: the CC BY 4.0 attribution, per file."""

    files, closures = bundled_file_table(parts)
    lines = [GENERATED_HEADER.format(archive_sha256=str(archive["sha256"]).split(":")[-1]), ""]
    lines.extend(
        [
            "/**",
            " * Per-file authorship and licence for every LDraw file whose geometry is",
            " * bundled, preserved rather than flattened. Reuse is not training: the mesh",
            " * provenance records `trainingUseAllowed: false` and this table is the",
            " * attribution the CC BY 4.0 licence requires.",
            " */",
            "export interface BundledLdrawSourceFile {",
            "  /** Path inside the official LDraw library, which is the file's identity. */",
            "  readonly path: string;",
            "  readonly bytes: number;",
            "  readonly sha256: `sha256:${string}`;",
            "  readonly title: string;",
            "  readonly author: string;",
            "  readonly ldrawOrg: string;",
            "  readonly licenseExpression: string;",
            "}",
            "",
            f"/** Every file in the {len(parts)} bundled closures, deduplicated and path-ordered. */",
            "export const BUNDLED_LDRAW_SOURCE_FILES: readonly BundledLdrawSourceFile[] = "
            "Object.freeze([",
        ]
    )
    for record in files:
        lines.append("  {")
        lines.append(f"    path: {_string(record.path)},")
        lines.append(f"    bytes: {record.byte_length},")
        lines.append(f"    sha256: {_string(record.sha256)},")
        lines.append(f"    title: {_string(record.title)},")
        lines.append(f"    author: {_string(record.author)},")
        lines.append(f"    ldrawOrg: {_string(record.ldraw_org)},")
        lines.append(f"    licenseExpression: {_string(record.license_expression)},")
        lines.append("  },")
    lines.append("]);")
    lines.append("")
    lines.append("/** Which of those files each bundled part's exact closure references. */")
    lines.append(
        "export const BUNDLED_LDRAW_CLOSURES: Readonly<Record<string, readonly number[]>> = "
        "Object.freeze({"
    )
    for design_id, indices in closures.items():
        lines.append(f"  {_string(design_id)}: [{', '.join(str(index) for index in indices)}],")
    lines.append("});")
    lines.append("")
    lines.append("/** The archive the files above were read from, byte-pinned. */")
    lines.append("export const BUNDLED_LDRAW_ARCHIVE = Object.freeze({")
    for key in ("archiveId", "source", "version"):
        lines.append(f"  {key}: {_string(str(archive[key]))},")
    lines.append(f"  bytes: {int(archive['bytes'])},")  # type: ignore[arg-type]
    lines.append(f"  sha256: {_string(str(archive['sha256']))},")
    lines.append("});")
    return "\n".join(lines) + "\n"
