"""Generated by generate-proper-orientation-tables.mjs. Do not edit."""

PROPER_ORIENTATION_ROWS: tuple[tuple[str, tuple[int, ...]], ...] = (
    ("upright-yaw-0", (1, 0, 0, 0, 1, 0, 0, 0, 1)),
    ("upright-yaw-90", (0, 0, 1, 0, 1, 0, -1, 0, 0)),
    ("upright-yaw-180", (-1, 0, 0, 0, 1, 0, 0, 0, -1)),
    ("upright-yaw-270", (0, 0, -1, 0, 1, 0, 1, 0, 0)),
    ("proper-m-00n0n0n00", (0, 0, -1, 0, -1, 0, -1, 0, 0)),
    ("proper-m-00nn000p0", (0, 0, -1, -1, 0, 0, 0, 1, 0)),
    ("proper-m-00np000n0", (0, 0, -1, 1, 0, 0, 0, -1, 0)),
    ("proper-m-00p0n0p00", (0, 0, 1, 0, -1, 0, 1, 0, 0)),
    ("proper-m-00pn000n0", (0, 0, 1, -1, 0, 0, 0, -1, 0)),
    ("proper-m-00pp000p0", (0, 0, 1, 1, 0, 0, 0, 1, 0)),
    ("proper-m-0n000np00", (0, -1, 0, 0, 0, -1, 1, 0, 0)),
    ("proper-m-0n000pn00", (0, -1, 0, 0, 0, 1, -1, 0, 0)),
    ("proper-m-0n0n0000n", (0, -1, 0, -1, 0, 0, 0, 0, -1)),
    ("proper-m-0n0p0000p", (0, -1, 0, 1, 0, 0, 0, 0, 1)),
    ("proper-m-0p000nn00", (0, 1, 0, 0, 0, -1, -1, 0, 0)),
    ("proper-m-0p000pp00", (0, 1, 0, 0, 0, 1, 1, 0, 0)),
    ("proper-m-0p0n0000p", (0, 1, 0, -1, 0, 0, 0, 0, 1)),
    ("proper-m-0p0p0000n", (0, 1, 0, 1, 0, 0, 0, 0, -1)),
    ("proper-m-n0000n0n0", (-1, 0, 0, 0, 0, -1, 0, -1, 0)),
    ("proper-m-n0000p0p0", (-1, 0, 0, 0, 0, 1, 0, 1, 0)),
    ("proper-m-n000n000p", (-1, 0, 0, 0, -1, 0, 0, 0, 1)),
    ("proper-m-p0000n0p0", (1, 0, 0, 0, 0, -1, 0, 1, 0)),
    ("proper-m-p0000p0n0", (1, 0, 0, 0, 0, 1, 0, -1, 0)),
    ("proper-m-p000n000n", (1, 0, 0, 0, -1, 0, 0, 0, -1)),
)

PROPER_ORIENTATIONS: dict[str, tuple[int, ...]] = dict(PROPER_ORIENTATION_ROWS)
